### ISSUE TITLE
optimizing and reducing energy impact 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#11]
I have several improvements in the queue ... this time energy ... still looking ahead for the vAmigaWeb ... which needs optimisations even more ... 

**Removal of that pixel rendering method via the windowsurface** 
in case the host does not support hardware accelerated GPU texture rendering we will notice this now and fall back to a software texture renderer...  So we got max. performance and high compatibility 

**Energy impact**
currently the mainloop is called 60 times in a second, hence 60fps ...
    it calls  60 times in a second c64->executeOneFrame();  is that neccessary ?
    and 60 times in a second it loads the screenbuffer c64->vic.screenBuffer(); into the GPU 
    and draws it 60 times per second onto the screen

When we modify the drawOneFrameIntoSDL() method so that it skips every second frame so that it effectively renders 30 fps  and it still looked the same as the 60 fps version 😎... 

By lowering to 30fps we save approximately **half** the CPU activity hence energy 🤓... The fans of my oldest machine do not turn on anymore 😍 

When we let run c64->executeOneFrame(); 60 fps  but only render the screenbuffer 30 fps then it saves still one third ...  which is also great !🤗 

I like to know how that is that handled in virtualC64? What is the recommended min. fps ? Is it valid to go by 30 fps only ? Am I eligable to do what I do ?... Sprite movments in fort apocalypse where absolutely smooth ...

**Comment by dirkwhoffmann** [comment]
> I like to know how that is that handled in virtualC64? 

The original emulator starts a 60Hz loop via the Metal API. In each iteration, the latest stable emulator texture is grabbed and fed into the GPU pipeline.

> Is it valid to go by 30 fps only ? 

To be honest, I don't expect texture copying to be a performance bottleneck. Your old code definitely was (I mean the code where you copied the texture manually pixel by pixel). But in the current implementation, you let the SDL do the copying (if I understand it correctly) and that should be fast. Nevertheless, it would be interesting to know how big the performance benefit really is. Just warp your old code with something like 

    counter++;
    if (counter % 2) "copy the Texture"

and we'll see. If 30Hz really brings a noticeable performance benefit, it could be added as an option later. But even then, I think it should have low priority, because we should definitely keep the 60Hz for modern browsers. 

BTW, I just encountered Javatari. Just played original PacMan in my browser a few minutes ago. This game was my very first contact with computers 😎. More than 40 years ago 😲.

<img width="668" alt="Bildschirmfoto 2020-04-10 um 20 25 20" src="https://user-images.githubusercontent.com/12561945/79016179-9d115800-7b6e-11ea-9fa1-ba1117b9b6ac.png">

**Comment by mithrendal** [comment]
```
counter++;
if (counter % 2) "copy the Texture"

```
I did already ...

>To be honest, I don't expect texture copying to be a performance bottleneck

on my old machine it did ... Maybe very old GPU

when I call the    
  c64->executeOneFrame();
only 30 fps all is smooth, energy saving is even greater ....  but sound a bit shabby 🙉

Have to check modern computers like the one from 2014

**Comment by dirkwhoffmann** [comment]
> but the skipping of the executeOneFrame() brings it down to 40 - 50 % ... 

Skipping `executeOneFrame()` every other frame means that you run the C64 at only 0.5 MHz 😯. Hence, sound is messed up. Video must be slower, too, but maybe it's not noticeable. This is also the reason why CPU load decreases so much 😃.

**Comment by mithrendal** [comment]
this is cool for games which are too fast or difficult 😎,  we can play them in slow motion then. 

![grafik](https://user-images.githubusercontent.com/17108995/79020338-dfd82d80-7b78-11ea-86ba-998c6873508d.png)

**Comment by mithrendal** [comment]
🥺

can you explain this ?

![Bildschirmfoto 2020-04-11 um 07 32 40](https://user-images.githubusercontent.com/17108995/79036306-4dab4600-7bc7-11ea-8925-f83e812892cb.png)

original vc64. I swear I have nothing done to it !🤞

**Comment by dirkwhoffmann** [comment]
> can you explain this ?

😯 Nope. Maybe it's because you are using an external alien monitor called "S.O.N.Y"... 

The main entrance point for drawing a single frame on the GPU is in MetalView.Swift:

```
    override public func draw(_ rect: NSRect) {
        
        if !enableMetal {
            return
        }
        
        // Wait until it's save to go ...
        semaphore.wait()
        
        // Refresh size dependent items if needed
        if layerIsDirty {
            reshape(withFrame: frame)
            layerIsDirty = false
        }
    
        // Draw scene
        drawable = metalLayer.nextDrawable()
        if drawable != nil {
            updateTexture()
            if fullscreen && !keepAspectRatio {
                drawScene2D()
            } else {
                drawScene3D()
            }
        }
    }
```

Could you insert the following lines at the very top of this function?

        let pfps = preferredFramesPerSecond
        track("\(pfps)")

On my machine, it returns a frame rate of 60. On your S.O.N.Y it might return 30? 🤔

Graphics programming is really some alien art and there are some fundamental things I still don't get. Let's say you have a laptop with a 60Hz TFT display. Now, let's connect this guy to an external TV with 50Hz and mirror the display. The question is: Is Metal calling MTKView::draw 60 times a second, or 50 times a second, or is the rendering frequency something completely different than the display frequencies of the monitor? 🤓

**Comment by mithrendal** [comment]
>Skipping executeOneFrame() every other frame means that you run the C64 at only 0.5 MHz 😯. Hence, sound is messed up. Video must be slower, too, but maybe it's not noticeable. This is also the reason why CPU load decreases so much 😃.

proofed
![grafik](https://user-images.githubusercontent.com/17108995/79037763-3a52a780-7bd4-11ea-8b58-7daa04012cb6.png)

without frameskip + skip execution 24 seconds

with frameskip and skip execution 12 seconds 

the c64 is a real computing beast ... 🙄

**Comment by dirkwhoffmann** [comment]
> the c64 is a real computing beast ... 🙄

Not only that. It's a perfect machine for quarantine. Here is a live stream from my home office: 

![5008f0c613259509a756b8588b245430](https://user-images.githubusercontent.com/12561945/79038141-4855f780-7bd7-11ea-8fe3-6b261d068990.jpg)

**Comment by mithrendal** [comment]
```
 let pfps = preferredFramesPerSecond
 track("\(pfps)")
```

moved into position and executed ...


results:
it tracked 60 but the vC64 this time reported in the bottom right corner 60Hz
🤔 

wait maybe I know why. The s.o.n.y is a 4k the mac mini 2014 can only handle 30Hz at that resolution. When I tested first I switched from 4k to 1080p to get the 60Hz. But vC64 still showed 30Hz.

Now that it shows the correct 60Hz ... I will switch it back to 4k 30Hz ... 

okay we will see what happens now .... wait ...

it still tracks 60Hz as preferred and shows in the lower right edge 30Hz...

**Comment by mithrendal** [comment]
just pushed the latest hottest stuff 😎

![grafik](https://user-images.githubusercontent.com/17108995/79051332-e9709c80-7c2f-11ea-9012-2e8dd6eeb334.png)

bottom line:
energy impact can not be reduced without quality loss... 
-that is when skipping rendering it is just 30 hz and not as fluent as is could be
-when skipping execution of a frame emulation is a slower C64

**Comment by dirkwhoffmann** [comment]
> just pushed the latest hottest stuff

Download in progress ... 🤤

Yeah, I like what I see... a perfect texture cutout... and fullscreen support in all browsers 🥳

<img width="1112" alt="Bildschirmfoto 2020-04-12 um 07 50 36" src="https://user-images.githubusercontent.com/12561945/79061773-b7912180-7c93-11ea-9717-2230bebc5d7a.png">

The game asks me to press the joystick button. We don't have joystick support yet, do we? 🙄

Oh, look, other customer reviews are coming in...

![cat](https://user-images.githubusercontent.com/12561945/79061840-633a7180-7c94-11ea-81f8-22091f91e4b8.png)

**Comment by mithrendal** [comment]
Oh yes man ... I already checked my controllers they are supported by html5 in firefox and safari  https://html5gamepad.com/  according to this site even ios13 safari supports this. So it might be even possible to play on an ipad with a wireless connected XBox or playstation Controller 😄

next I have to make implement the wasm_joystick ... interface  should all be straight forward... 



Does the VIC has a property or way which can tell us easily (with out comparing the buffer with the old buffer) whether the screenbuffer has changed at all ? Yes or No please...

**Comment by dirkwhoffmann** [comment]
> next I have to implement the wasm_joystick ... interface should all be straight forward...

Yes yes yes 🦾

> whether the screenbuffer has changed at all ?

No, there is no chance of knowing that. VIC would have to do the comparison by itself (which is too time consuming). It simply renews the texture every frame.

**Comment by mithrendal** [comment]
>No, there is no chance of knowing that. VIC would have to do the comparison by itself (which is too time consuming). It simply renews the texture every frame.

that is ok, then we close this issue ... BTW I am happy with performance in total ... but with the outlook to even game on a battery driven device, Smartphones or Tablets, with a connected game controller whe should also check the energy waste, to prevent it where possible ... 😇

**Comment by mithrendal** [comment]
some other C64web versions 

macbook pro 2007 firefox c64 blue start screen performance 😎

[pure javascript (not fully compatible)](https://github.com/mborgbrant/c64js) at http://mborgbrant.github.io/c64js/          90% load 

[vice2.4 codebase ](https://github.com/rjanicek/vice.js) at https://vice.janicek.co/c64/index.html   103% load

[wasm port of a not cycle exact therefore not fully compatible c64 emulator](https://c64emulator.111mb.de/index.php?site=pp_javascript&lang=de&group=c64) with 37% load 

compared to that vC64web is a high compatible energy saver with only 70% load

**Comment by dirkwhoffmann** [comment]
Wow, I didn't know there is a web version of VICE. Hmm... well... don't know what I did here... 🥴

<img width="792" alt="Bildschirmfoto 2020-04-15 um 15 19 36" src="https://user-images.githubusercontent.com/12561945/79345485-7a49bf80-7f31-11ea-83bc-1fa719cd093e.png">

But the controls are looking good 🤠.

Good to see that VirtualC64 performs better than VICE. (But VICE has rasterlines, VirtualC64 has not).

**Comment by mithrendal** [comment]
Do you mean it has no scan line effect or this https://www.google.de/amp/s/digitalerr0r.net/2011/04/30/commodore-64-programming-6-raster-interrupts/amp/
?

**Comment by dirkwhoffmann** [comment]
> Do you mean it has no scan line effect 

Yes. Maybe VICE would be slightly faster if the effect is disabled. In VirtualC64, all graphics effects are applied inside the GPU pipeline and can't be activated in VirtualC64web. But 103% to 70% is really something 😃. Forget about the non-cycle-exact C64 emulators... they are only capable of running very simple games.

**Comment by mithrendal** [comment]
I am curious whether vAmigaWeb can beat SAE performancewise ...

**Comment by dirkwhoffmann** [comment]
> I am curious whether vAmigaWeb can beat SAE performancewise ...

Let's do a rough calculation...

Depending on the emulated gamesor demo, VirtualC64 usually runs with 3 MHz - 9 MHz in warp mode on my machine. vAmiga usually runs at 20 MHz - 60 MHz in warp mode (very rough estimates). Divided by the native frequency results is a warp factor of approx. 3 - 9 in both cases. Therefore I expect vAmigaWeb to range at 70%, too. 😎
