### ISSUE TITLE
joystick connection properties

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#13]
![grafik](https://user-images.githubusercontent.com/17108995/79102310-c8609680-7d6a-11ea-9745-d7fb265d8dd5.png)

😎 now you are no longer stuck at 
![grafik](https://user-images.githubusercontent.com/17108995/79102442-0a89d800-7d6b-11ea-96ee-aa81a85df802.png)

next I am heading for connecting the REAL joysticks ...😜

... but this games mission has to be completed first .. rambo has to save the world ... again 

![grafik](https://user-images.githubusercontent.com/17108995/79104963-f5637800-7d6f-11ea-986b-801784708e22.png)

**Comment by dirkwhoffmann** [comment]
Works like a charm. It's totally fluent in Safari in full screen mode 😎. Scramble was one of my favorite games. Loved it 😍. 

  
<img width="1383" alt="Bildschirmfoto 2020-04-13 um 18 58 41" src="https://user-images.githubusercontent.com/12561945/79140881-f967b800-7db8-11ea-8890-dbcc7d42454e.png">

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/79155703-d5fd3700-7dd1-11ea-9bc5-11843182efa9.png)

connected a good old competition pro to vC64web !! 😎

and added an reset button...

strangly when I go to the website I have to connect the gamepad  after vc64web is loaded ... only then html5 sends me an connected event ... Maybe it is already there when it is already connected and therefore it sends me no "connected" event 🤔

**Comment by dirkwhoffmann** [comment]
> only then html5 sends me an connected event ...

I guess you need to 
- either register as some kind of USB listener or
- poll the connected USB devices when virtualC64web launches

If I remember correctly, the first method is used in original VirtualC64. I forgot about the details, because talking to USB devices in macOS is 🤢. It can be completely different in a browser though.

**Comment by mithrendal** [comment]
houston I have a problem ... choplifter works fine but ... fort apocalypse which yesterday worked ... today makes troubles ... the game sends thousands of MSG_CHARSET messages which are written to the output of the HTML textarea and is slowing down the game ... once I deactivate the log output completely , the game runs fine with gamepad controllers 
The question is why is the core sending me this message I bet yesterday it did not so ... other games do not so either ...

**Comment by dirkwhoffmann** [comment]
Background: MSG_CHARSET informs the GUI that the C64 switches from lower case character mode to upper case character mode or vice versa. When this message arrives in original VirtualC64, the key caps on the virtual keyboard are updated. (Maybe it would be better to poll this bit. I didn't expect a program to switch it that frequently...)

      case 0x18: // Memory address pointers
            
            // Inform the GUI if the second bit changes. It switches between
            // upper case or lower case mode.
            if ((value & 0x02) != (memSelect & 0x02)) {
                memSelect = value;
                c64->putMessage(MSG_CHARSET);
                return;
            }
            
            memSelect = value;
            return;

Are you sure the game didn't send the messages yesterday? 🤔 If the game does work, I don't think it's a bug. Maybe it's best just to omit the output for this message in the debug function.

BTW, did you already check in the latest changes? I tried with the current code on the gamepad branch. It does recognize my USB competition Pro if I plug it in after VC64web has launched, but I cannot steer my fighter with it 😪.

**Comment by mithrendal** [comment]
>MSG_CHARSET

ok I will ignore MSG_CHARSET then it works well

>but I cannot steer my fighter with it 

Do you see output in the debug textarea ?

**Comment by dirkwhoffmann** [comment]
> Do you see output in the debug textarea ?

I can see the messages in Firefox. But they don't show up in Safari.

**Comment by mithrendal** [comment]
😁only tested in firefox .... does your gamepad show up in  https://html5gamepad.com/ with safari are the axes changing when you move the joystick ?

**Comment by dirkwhoffmann** [comment]
More observations (all actions are performed after VC64web has been launched)

Firefox: 
Connecting joystick to USB port: Joystick does *not* show up in menu
Pressing button: Joystick does show up in the menu

Safari:

Connecting joystick to USB port: Joystick does show up in menu
Pressing button: Joystick does *not* show up in the menu

**Comment by dirkwhoffmann** [comment]
Yes, it shows up: 

<img width="717" alt="Bildschirmfoto 2020-04-13 um 22 47 27" src="https://user-images.githubusercontent.com/12561945/79159675-cb926b80-7dd8-11ea-8fa1-9ff4d401675d.png">

**Comment by mithrendal** [comment]
are the numbers of the axes changing in https://html5gamepad.com/  ?

**Comment by dirkwhoffmann** [comment]
Yes, numbers are changing.

**Comment by dirkwhoffmann** [comment]
Numbers vary from -1 to 1. Strange enough, idle is not 0, but 0.00392.

**Comment by mithrendal** [comment]
then I do something wrong in safari 🙄   let me check on my machine...

But in firefox you can play right ?

**Comment by dirkwhoffmann** [comment]
> But in firefox you can play right ?

Yes, but only PRG files are working. T64 support is broken 🤭.

**Comment by mithrendal** [comment]
gamepad: yes I on my safari (macos catalina) too. Same story. Strangely sometimes the webpage https://html5gamepad.com/ does not recognize them either or axis values are not changing 😶...

T64 have not done it ...😇  later ... tomorrow 😅

**Comment by dirkwhoffmann** [comment]
>  tomorrow 😅

🥱 Need to get some sleep, too. Tell Rambo to refuel the chopper. We'll need it tomorrow.

**Comment by mithrendal** [comment]
I tested various other websites with gamepad support on safari. They all sometimes are not working. Safari even crashed several times... One showed the same behaviour as our vc64web constantly having PULL_UP and PULL_LEFT on.  Upon several restarts of the safari ... switching the gamepad physically out of the usb port and reinserting it ... pressing some buttons they finally worked. And so is the vc64web ... it works somewhen occasionally like the other websites which use gamepads ... So I believe more and more it is the safari browser who has buggy gampad support.

Firefox shows consistent behaviour...

What about chrome ?

**Comment by dirkwhoffmann** [comment]
> What about chrome ?

Firefox: 👍
Chrome: 👍
Safari: 👎

Safari also has problems running Javatari. I'm missing Steve so much 😪.

BTW, are you using a real Competition Pro from back in the day with a retro adapter, or a fake Competition Pro USB? There seems to be a newer fake USB variant on Amazon (SL-650212) which is told to have better reaction times 🤤. Unfortunately, I cannot find the information about the improved reaction time any more, but it was there... somewhere...

**Comment by mithrendal** [comment]
![A9D75EFD-2199-4ACB-A69D-B78792A7810D](https://user-images.githubusercontent.com/17108995/79307383-199d9100-7ef7-11ea-80cb-425556fb9f11.jpeg)

![D14851D8-CC13-47EA-8A8E-ACF9A023282D](https://user-images.githubusercontent.com/17108995/79307386-1b675480-7ef7-11ea-9689-a0ec87975024.jpeg)

**Comment by mithrendal** [comment]
There are some gampad API wrappers ... I think we don't need them ... but they are a good place to spot problems ... one reports of change in API since chrome 78 where navigator.getGamePads() returns a list instead of an array ...

the fix is very easy see here 
https://github.com/ArunMichaelDsouza/joypad.js/issues/1

but unless this is really a problem I don't like to change the simple straightforwardness of the our code... 

which version of chrome did you test with  ?

**Comment by dirkwhoffmann** [comment]
I've got the exactly same Competition Pro USB model. 

Chrome 80.0.3987.163 (wow, what a cool versioning scheme 😎)

**Comment by dirkwhoffmann** [comment]
Came in yesterday. The new model seems to have much better reaction times... 🤤

![IMG_0924](https://user-images.githubusercontent.com/12561945/79995915-205c7300-84b8-11ea-8710-7232cc3047d9.JPG)

**Comment by mithrendal** [comment]
The new USB joysticks have a design flaw I think. That is the two additional buttons in triangle shape... In heavy action .... I  do press the left triangle accidently when steering to the right ... because my left hands thumb holds it just where that triangle button is... I will change that in the joystick event ... there I know exactly which button and I will let that button not trigger fire ...
