### ISSUE TITLE
going responsive and making some glitter

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#20]
I played a bit with a minimalistic css framework called [skeleton](http://getskeleton.com/) it only consists of two files with the size of a few Kb and no Javascript.
![grafik](https://user-images.githubusercontent.com/17108995/80301614-58f49900-87a5-11ea-8acd-a843d98feea5.png)

and on a small device
![grafik](https://user-images.githubusercontent.com/17108995/80301628-6578f180-87a5-11ea-8dcf-74a8d9c61ad0.png)

But maybe when we do the snapshot storaging we need some more nice looking gui components like  alerting or short modal messages/dialogs . 

We should maybe better go for a css framework with more and richer components like bootstrap...

I have found another cool framework which gives it a retro look ... it is called [NES.css](https://nostalgic-css.github.io/NES.css/) but it is a bit too NES like ... no?

**Comment by dirkwhoffmann** [comment]
> we need some more nice looking gui components 

Yes, we are at a crucial point here: Most browser GUI components are plain ugly 😬. A major selling point of VirtualC64 is that is looks cooler than most other emulators, and we should try to preserve that selling point for the web version as much as we can. 

For finding a suitable framework, I suggest to forget about the framework at all. Watch out for cool looking web pages. Once such a page is found, try to find out the details about the underlying framework. 

Based on my experience from the past, retro looking frameworks don't have the effect they are supposed to have (e.g., have a look at the Stella GUI on macOS). It's much more impressive to embed the retro stuff (emulator) inside a futuristic looking surrounding.

**Comment by mithrendal** [comment]
on a computer
![grafik](https://user-images.githubusercontent.com/17108995/82600349-152b5e80-9bae-11ea-913a-bfc5d0b8841f.png)
