### ISSUE TITLE
Space on an iPhone or iPad

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#21]
![03A23913-CAF0-44E8-8DE1-9F562E57C410](https://user-images.githubusercontent.com/17108995/82604130-18294d80-9bb4-11ea-8af4-e23c550f1ec6.png)

Here you see me on a 6s plus controlling the heli with a bluetooth keyboard in fullscreen (ALT+ENTER)

Everything is good. But in NON-fullscreen
The space key scrolls the screen down ... must be a specific iOS feature...

![A3CC5E8A-0803-4367-9DB4-8832B508B789](https://user-images.githubusercontent.com/17108995/82604450-a4d40b80-9bb4-11ea-89ae-66ef9948212b.png)

**Comment by mithrendal** [comment]
I found the problem ... I had to call preventDefault() on keyboard events to prevent the default that scrolls the screen down on space key press on iOS

**Comment by dirkwhoffmann** [comment]
So cool to see Virtual64web being responsive now 😎.
