### ISSUE TITLE
should we have a darkmode switch ?

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#24]
someone told me once about the art of  PISDM(TM) (Priority Inversion Software Development Method) aka LITF: least important things first 👍🏼
... I wanted to try this too 😎 ... therefore I thought of the least important thing which vc64web needs now ... which I think 🤔 is a ... darkmode switch ...

here are some impressions of the hack ...

![grafik](https://user-images.githubusercontent.com/17108995/82843033-19bc8380-9edc-11ea-98e3-e1d8be822fef.png)

![grafik](https://user-images.githubusercontent.com/17108995/82843044-250faf00-9edc-11ea-9dd2-efb04fdd71b3.png)

![grafik](https://user-images.githubusercontent.com/17108995/82843657-1aeeb000-9ede-11ea-89ee-e9e5f606f2f8.png)

![grafik](https://user-images.githubusercontent.com/17108995/82843047-2c36bd00-9edc-11ea-8ac2-befde6b95563.png)

I don't know now whether I should commit or discard the dark mode switch ? Because it is just so unimportant...

**Comment by dirkwhoffmann** [comment]
VC64web in dark mode 🤤

> Because it is just so unimportant...

Dark mode unimportant? No way!!! I have would have started with this features right away. I was already wondering why it is coming so late... 🤔

**Comment by mithrendal** [comment]
the light side ... 

![grafik](https://user-images.githubusercontent.com/17108995/83073784-4fdf3c00-a071-11ea-9ee9-365e976800b2.png)



and the dark side ... 

![grafik](https://user-images.githubusercontent.com/17108995/83073901-8321cb00-a071-11ea-94cc-f4526238bf4f.png)


polished .... ready to commit 😎
