### ISSUE TITLE
support of tape files

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#29]

**Comment by mithrendal** [comment]
now that we support the "one-click-install" of the open roms ... we should make tape files work (because the user most likely cannot afford a disk drive ... like in the old days)

**Comment by dirkwhoffmann** [comment]
> we should make tape files work

Yes yes yes. I remember when my cousin and me loaded the first game from tape. We stared at the blank screen for minutes. It was so thrilling to see... nothing, but a light blue background 😂.

**Comment by dirkwhoffmann** [comment]
> any hints ? is it like the with other files or do I have to do something special here ?

Unfortunately, I haven't looked at the datasette code for years 😬. Below is the API. From the functions listed, you need 'insertTape()'. Use it the same way as you used 'attachCartridg()'. It is also necessary to emulate the play key and the stop key. Use 'pressPlay()' and 'pressStop()' for that. You also might want to use 'rewind()' to rewind the tape. 

 ```
  //
    // Handling virtual tapes
    //
    
public:
    
    // Returns true if a tape is inserted
    bool hasTape() { return size != 0; }
    
    //Inserts a TAP archive as a virtual tape
    bool insertTape(TAPFile *a);

    // Ejects the virtual tape (if any)
    void ejectTape();

    // Returns the tape type (TAP format, 0 or 1).
    u8 getType() { return type; }

    // Returns the tape length in cycles.
    u64 getDurationInCycles() { return durationInCycles; }
    
    // Returns the tape length in seconds.
    u32 getDurationInSeconds() { return (u32)(durationInCycles / (u64)PAL_CLOCK_FREQUENCY); }

    
    //
    // Operating the read/write head
    //

    // Puts the read/write head at the beginning of the tape
    void rewind() { head = headInSeconds = headInCycles = 0; }

    /* Advances the read/write head one pulse. This methods updates head,
     * headInCycles, and headInSeconds. If silent is set to false, a
     * MSG_VC1530_PROGRESS message is sent.
     */
    void advanceHead(bool silent = false);
    
    // Returns the head position
    u64 getHead() { return head; }

    // Returns the head position in CPU cycles
    u64 getHeadInCycles() { return headInCycles; }

    // Returns the head position in seconds
    u32 getHeadInSeconds() { return headInSeconds; }
    
    // Sets the current head position in cycles.
    void setHeadInCycles(u64 value);
    
    // Returns the pulse length at the current head position
    int pulseLength(int *skip);
    int pulseLength() { return pulseLength(NULL); }

    
    //
    // Running the device
    //
    
    // Returns true if the play key is pressed
    bool getPlayKey() { return playKey; }

    // Press play on tape
    void pressPlay(); 

    // Press stop key
    void pressStop();

    // Returns true if the datasette motor is switched on
    bool getMotor() { return motor; }

    // Switches the motor on or off
    void setMotor(bool value);

    // Emulates the datasette
    void execute() { if (playKey && motor) _execute(); }

private:

    // Internal execution function
    void _execute();

    // Simulates the falling edge of a pulse
    void _executeFalling();

    // Simulates the rising edge of a pulse
    void _executeRising();
```

**Comment by mithrendal** [comment]
Lets get the good old datasette working ... 


do insert some good code here 
```
  else if (checkFileSuffix(name, ".TAP")|| checkFileSuffix(name, ".tap")) {
    printf("isTAP\n");
    wrapper->c64->datasette.insertTape(TAPFile::makeWithBuffer(blob, len));
    wrapper->c64->datasette.rewind();
    wrapper->c64->datasette.pressPlay();
    wrapper->c64->datasette.pressStop();
  }
```

oh yes it compiles .... that was so easy !



now insert the tape 
load"archon",1,1
now insert the tape

![grafik](https://user-images.githubusercontent.com/17108995/90679947-496ff300-e261-11ea-85e4-828afa7679fe.png)


it says I should press play ... but didn't I ? Maybe the mechanics is wrong ? ...

**Comment by dirkwhoffmann** [comment]
>  wrapper->c64->datasette.pressPlay();
>  wrapper->c64->datasette.pressStop();

You pressed play and a micro-yotta later, you pressed pause 😬. Try to press play, only. 

It might be necessary to delay pressing 'play' for a second or so. I don't remember.

rewind() shouldn't be necessary after inserting. It's already rewinded.

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/90680809-b8018080-e262-11ea-9f21-e5c1c7b35ef0.png)

**Comment by mithrendal** [comment]
Oh my good after three minutes or so it stoppen ... can I play archon now ?


![grafik](https://user-images.githubusercontent.com/17108995/90681121-2f371480-e263-11ea-8194-31da0946e879.png)


no ... something stranged happened ...

**Comment by dirkwhoffmann** [comment]
> something strange happened ...

😮 Can you try in VirtualC64mac? I guess it'll crash, too. 😬

**Comment by mithrendal** [comment]
I will do ... in the meantime I try frogger ...

**Comment by mithrendal** [comment]
Ok I stop it on vc64web and try first vc64mac  because it seems that it loads forever ....

**Comment by dirkwhoffmann** [comment]
I'm loading Galaxy right now 🤤

**Comment by dirkwhoffmann** [comment]
Galaxy.tap works. Just loaded from tape 😎

<img width="931" alt="Bildschirmfoto 2020-08-19 um 21 50 28" src="https://user-images.githubusercontent.com/12561945/90682930-0a906c00-e266-11ea-89c2-9949fa9dda86.png">

**Comment by mithrendal** [comment]
oh that was fast ... definitely something wrong how I operate the system ... wait I have to learn first with the big brother vc64mac ... loading frogger there now

**Comment by mithrendal** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/17108995/90683475-e3866a00-e266-11ea-8874-115d2e0358c4.png">



huh auto load ... auto play ... am I missing something in vc64web ?  

lets play ...

**Comment by mithrendal** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/17108995/90683681-3b24d580-e267-11ea-9437-ad8118f95fb3.png">


look here it is different it is already ready and on vc64web it loads frogger 64 .. part1 ...part2 .... part3

Maybe the name in `load "the_name",1,1` must match the file on tape ?

**Comment by mithrendal** [comment]
the gurus on the net say 

```
Tapes
To load a tape, simply insert the tape, rewind it, then type LOAD and hit return, or hit the shift-Run/Stop key combination.

If a tape has more than one game on it, rewind it, type LOAD “7”,1 and hit return. As the computer finds files, it will print the names. To load a specific title, type LOAD “filename”,1 and hit return, then type RUN.

That’s how to load Commodore 64 games from tape.
```

**Comment by dirkwhoffmann** [comment]
Here is a portion of the Swift code (TapeMountController.swift):

```
          let kbc = myController?.keyboard
            
            if autoPress.integerValue == 1 {
                kbc?.type(string: "LOAD\n", completion: proxy?.datasette.pressPlay)
            } else {
                kbc?.type(string: "LOAD\n", completion: nil)
            }
```

Auto-load simply types LOAD <Return>. After typing, play is pressed. You don't have to press stop until the normal screen is visible again.

**Comment by dirkwhoffmann** [comment]
Maybe, you have a different Frogger... try these:

[Frogger 64.tap.zip](https://github.com/dirkwhoffmann/virtualc64web/files/5099004/Frogger.64.tap.zip)
[Galaxy.tap.zip](https://github.com/dirkwhoffmann/virtualc64web/files/5099005/Galaxy.tap.zip)

Both load well in VC64mac. 

<img width="931" alt="Bildschirmfoto 2020-08-19 um 22 09 42" src="https://user-images.githubusercontent.com/12561945/90684553-b470f800-e268-11ea-96ae-6a23e6cbcca1.png">

**Comment by mithrendal** [comment]
frogger 64 loaded in vc64mac but when I typed run it wants to load part1 to part4 which takes also forever ...

I guess me as a beginner I better start with galaxy.tap now ...  in 1985 or so I was so good at it do you believe me ?

**Comment by mithrendal** [comment]
oh no frogger is there I mean that thing what loaded forever .....

**Comment by dirkwhoffmann** [comment]
> oh no frogger is there I mean that thing what loaded forever .....

This means it has loaded?

**Comment by mithrendal** [comment]
yes in vc64mac ... it takes years to load ... now galaxy is there too on c64mac

ok what do I have to do on vc64web .. what did I learn ...

1. only type "load"
2.insert tape 

and that should work no ?

I will try now with galaxy

**Comment by dirkwhoffmann** [comment]
Insert the tape first. After that type "LOAD". After that press play.

**Comment by mithrendal** [comment]
I did typed "load" ... dragged the .tap file in file slot and then it loads automatically ... I see a brown screen now ...

... and 

![grafik](https://user-images.githubusercontent.com/17108995/90686617-e46dca80-e26b-11ea-9457-4891e72159f7.png)


....it finished with

![grafik](https://user-images.githubusercontent.com/17108995/90686724-0f581e80-e26c-11ea-917a-c6f9bff14acf.png)


I have to do a snaphot on this one .... 


![grafik](https://user-images.githubusercontent.com/17108995/90686536-c7d19280-e26b-11ea-8754-61a4fa0d8fb6.png)

**Comment by dirkwhoffmann** [comment]
Very cool 🤩

**Comment by mithrendal** [comment]
do you think we have to change the operating of tapes ?

when I drag a tap file I could 

first insert tape 
then emit the keycodes 

"return" and then "l", "o", "a", "d", "return"

and then pressPlay ?

**Comment by mithrendal** [comment]
pushed the current working version to gh-pages

**Comment by dirkwhoffmann** [comment]
1. first insert tape
2. then emit the keycodes
3. "return" and then "l", "o", "a", "d", "return"

This is what the user would do on a real machine, I think (in this order). Hence, I think it's better to use that order. Then, it would be consistent with the desktop version, too. 

I've just opened a bug report about the Archon crash here: 
https://github.com/dirkwhoffmann/virtualc64/issues/579

**Comment by mithrendal** [comment]
I think what swift is for vc64mac that is javascript for vc64web
`
 kbc?.type(string: "LOAD\n", completion: proxy?.datasette.pressPlay)`

so  emitting key codes is more convenient in javascript I think because I have to serialize the string "load<return>" with timings for keydown and keyup of each single character so I think it is better to do this in javascript and additionally to export the press play method to javascript ...

or do you know a better way in c, how to insert a complete string into the core  ?

lets do it tomorrow ...

**Comment by mithrendal** [comment]
Hmm open roms don’t like Archon tape ... it was loading... but result was empty 

![F4D68973-E30D-44FA-AD3E-FE317822D016](https://user-images.githubusercontent.com/17108995/90718838-3be35900-e2b3-11ea-8c4a-e77bf153c223.png)

**Comment by mithrendal** [comment]
![912F3BB5-6489-4492-8F93-69FFEA333403](https://user-images.githubusercontent.com/17108995/90723942-f7a98600-e2bd-11ea-87bf-e4d31215af7d.png)

![7E2985D1-E105-45C3-A911-ED317322B07D](https://user-images.githubusercontent.com/17108995/90723990-08f29280-e2be-11ea-9e99-117564835d75.png)



😎

**Comment by mithrendal** [comment]
🙈

Tried it a second time
![5A104789-31AD-4C1C-A9AE-2EEA958140B8](https://user-images.githubusercontent.com/17108995/90724677-3724a200-e2bf-11ea-9b41-7e4aa7b8c2f5.png)

A third time
![2E4AF3B0-966E-421D-975C-BDC5264A0EDB](https://user-images.githubusercontent.com/17108995/90724725-4572be00-e2bf-11ea-8877-4f65da60baa3.png)

**Comment by dirkwhoffmann** [comment]
How ist that possible? Did you rewind the tape?

**Comment by mithrendal** [comment]
I coldstarted with every try ... I will try WASM optimization level 1 or even 0

**Comment by mithrendal** [comment]
compiled the core with -O0 (no optimizations at all) 

very slow ... fans ram up immediately ... CPU on 95% (instead 56%) on my old 2007 flag ship ...  

result ...
![grafik](https://user-images.githubusercontent.com/17108995/90728234-d8fabd80-e2c4-11ea-959e-0b45423faba1.png)


that is good news I think ... must be something else then ... do we have to increase the debug level of the datasette now?

**Comment by dirkwhoffmann** [comment]
> Load error ... I love that ...

Yes, emulation is super realistic. Sometimes the datasette works and sometimes not 😂

> do we have to increase the debug level of the datasette now?

I don't remember if there is much debug output. The datasette is rarely used and I haven't looked into the code for years 🙄.
The strange thing is that it seems to work in the desktop version. 🤔

You type "LOAD" *before* pressing PLAY, right?

**Comment by mithrendal** [comment]
I tried "load" before pressing play and the other way around ...

>The strange thing is that it seems to work in the desktop version. 🤔

also with open roms ? we have to check vc64mac with open roms loading this one from tape  ... maybe a problem in openroms ? 
I guess vc64mac will have problems because this
kbc?.type(string: "LOAD\n", completion: proxy?.datasette.pressPlay)

will not work in open roms ... they mapped "load" to disk drive by default...

**Comment by dirkwhoffmann** [comment]
> also with open roms ?

Never tried that...

>  they mapped "load" to disk drive by default...

So we need to use "<-L" ?

**Comment by mithrendal** [comment]
>So we need to use "<-L" ?

yes I think ... 


I just tried the original commodore roms and look at this ...

![grafik](https://user-images.githubusercontent.com/17108995/90730220-0bf28080-e2c8-11ea-92c2-fd1cf2dbf546.png)

it loaded galaxy successfully from tape ...

could be really also a open roms problem ....

**Comment by dirkwhoffmann** [comment]
> (but still there is the archon problem ...

I'll look into that ...

> could be really also a open roms problem

We should get rid of of the indeterminism (which is strange anyway). Sometimes it works, sometimes not. Maybe vc64web can be patched to immediately load from tape when it is startet. I do a similar thing in vAmiga for debugging to get rid of any indeterminism caused by user interaction.

**Comment by dirkwhoffmann** [comment]
Which Archon TAP file did you use? I only found Archon 2 so far. 

I already know what the bug is, I think. Archon must be a type-1 TAP file.

**Comment by mithrendal** [comment]
> Maybe vc64web can be patched to immediately load from tape when it is startet

yes I will do ...

[archon2 tape](https://www.c64games.de/phpseiten/spieledetail.php?filnummer=17)

**Comment by dirkwhoffmann** [comment]
Thanks! 

First, I try to reproduce the crash... it's loading ... loading ... loading ... 🥱

**Comment by mithrendal** [comment]
L ..... O .... A .....D ....I.... 

![grafik](https://user-images.githubusercontent.com/17108995/90686617-e46dca80-e26b-11ea-9457-4891e72159f7.png)


....N ....G

**Comment by dirkwhoffmann** [comment]
```
Tape counter: 14 (35381 out of 513434)
Tape counter: 15 (37383 out of 513434)
Tape counter: 16 (40060 out of 513434)
Tape counter: 17 (42358 out of 513434)
Tape counter: 18 (44533 out of 513434)
Tape counter: 19 (46701 out of 513434)
Tape counter: 20 (48362 out of 513434)
...
```

![Screen Shot 2014-12-18 at 7 52 57 pm](https://user-images.githubusercontent.com/12561945/90755310-487ba780-e2db-11ea-9b2e-6b2d4b02acba.png)

Maybe we should look for a smaller test case. This Archon game is HUUUUUGEEEE.

**Comment by dirkwhoffmann** [comment]
236 seconds later 🥵

```
Tape counter: 229 (497427 out of 513434)
Tape counter: 230 (499615 out of 513434)
Tape counter: 231 (501734 out of 513434)
Tape counter: 232 (504054 out of 513434)
Tape counter: 233 (506520 out of 513434)
Tape counter: 234 (508610 out of 513434)
Tape counter: 235 (510673 out of 513434)
Tape counter: 236 (513178 out of 513434)
Datasette: Datasette::pressStop
```

It does no longer crash, but the screen remains light blue. I don't remember what a real datasette would do in this case.

**Comment by dirkwhoffmann** [comment]
I've checked in the fix on the v3.4 branch.

**Comment by mithrendal** [comment]
Is .T64 also a tape format? Can not insert it into the datasette 🙈. Datasette API insertTape complains that it is not the right device for those files. 

`bool insertTape(TAPFile *a);`

**Comment by dirkwhoffmann** [comment]
> Is .T64 also a tape format?

No, T64 is a very misleading name. It is an archive containing the binary representations of multiple files. You can either flash a file from a T64 archive into memory, or you can convert a T64 file into a disk and insert it into the VC1541. You cannot convert T64 to TAP. In case of the OpenRoms, flashing is the only option.

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/90785038-32351200-e302-11ea-82f7-0a591db346e9.png)

flashing a t64 file works ...

**Comment by mithrendal** [comment]
still need a mechanism to auto start the files ... I already have an idea how to do this ... 

every flashed file emit "<return>", "run" 
on .tap files 
    first insert tape
    then emit the keycodes
    "<RETURN>", "SHIFT" and then "RUN-STOP"  which triggers tape LOAD on both commodore rom and open rom

**Comment by mithrendal** [comment]
they fixed it with the latest open roms ...

tape loading works now ... I close it
