### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#3]
I just listened to the sound of octopus in red wine in firefox. Oh my god it really works 🙈.  I made a branch sound for it. 🥁🎻🎺🎸🪕

**Comment by dirkwhoffmann** [comment]
🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙 
👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by dirkwhoffmann** [comment]
> I have an older version of emscripten on macos, which I downloaded two years ago and it is still working fine, never upgraded.

Are you still using the old version? I am asking because I had trouble installing wasm  on macOS when I did my wasm Moira experiments and I am wondering how you did it.

**Comment by mithrendal** [comment]
No I completely removed that installation. I installed 10 days ago the current version of emsdk. I did it via the pure git way which is described at the [emscripten site under install instructions](https://emscripten.org/docs/getting_started/downloads.html). 
```
# Get the emsdk repo
git clone https://github.com/emscripten-core/emsdk.git

# Enter that directory
cd emsdk

# Fetch the latest version of the emsdk (not needed the first time you clone)
git pull

# Download and install the latest SDK tools.
./emsdk install latest

# Make the "latest" SDK "active" for the current user. (writes ~/.emscripten file)
./emsdk activate latest

# Activate PATH and other environment variables in the current terminal
source ./emsdk_env.sh
```

In that emsdk dir I just did a 
```

git clone https://github.com/dirkwhoffmann/virtualc64web.git vc64web

cd vc64web 

make
make main
 
and so on...
```

**Comment by dirkwhoffmann** [comment]
Do the Rom files in folder `roms/` need to have specific names? I am stuck with a MSG_ROM_MISSING message 🥴.

**Comment by mithrendal** [comment]
yes, have a look into mainsdl.cpp. Should we upload the roms into github ? I did cast a gitignore on them because you I think wrote somewhen that they are still copyrighted ....

**Comment by dirkwhoffmann** [comment]
> I did cast 🧟‍♀️ a gitignore

Well done 👍.

> Should we upload the roms into github ?

Noooooo 😲. Don't want to get sued...

**Comment by mithrendal** [comment]
if you want maximum performance on modern systems do build the SDL2 WEB-GL Texture version

in C64/C64.cpp comment USE_SDL_2_PIXEL and activate USE_SDL_2_TEXTURE 
```
//#define USE_SDL_2_PIXEL 1
#define USE_SDL_2_TEXTURE 1
```

I use the USE_SDL_2_PIXEL build to develop on an very old mac laptop which does not support WEBGL.


I played with the sound buffer sample length 256 and 512 are fine... length of 64 does not work ...

**Comment by dirkwhoffmann** [comment]
Houston, we've got a problem 😬.

First, the good news: I did manage to run the Octopus in Safari 😋.

<img width="1317" alt="Bildschirmfoto 2020-03-13 um 13 02 55" src="https://user-images.githubusercontent.com/12561945/76621346-78a26b80-652f-11ea-82d4-0c14a41c621e.png">

After that, I tried with Fort Apocalypse (which is a T64 file). It constantly throws an out of memory exception, although I increased the available memory in the Makefile to `-s TOTAL_MEMORY=1024MB`. Here is what the Chrome debug console says:

<img width="563" alt="Bildschirmfoto 2020-03-13 um 13 33 38" src="https://user-images.githubusercontent.com/12561945/76621472-b69f8f80-652f-11ea-9cbf-5e06afb8afaa.png">

**Comment by mithrendal** [comment]
Why do you not see the message text for the msg_codes  ? Is something broken ?
`printf("incoming message=%s, data=%ld\n", msg_code[type].c_str(), data); `
but
  output  is _incoming msg=9, data=0_ 


>After that, I tried with Fort Apocalypse (which is a T64 file).

Yes Fort Apocalypse my favourite.   I only implemented flash support, did you implement T64 support ?

>It constantly throws an out of memory exception, although I increased the available memory in the Makefile to -s TOTAL_MEMORY=1024MB. 

Try to disable sound, maybe something wrong with soundbuffer and sound consumes all memory ??
->temporarily uncomment the AUDIO stuff in C64/C64.cpp

**Comment by mithrendal** [comment]
Now I see it does not complain about not enough memory, it is about memory access.

try to outcomment 
```
void MyAudioCallback(void*  thisC64,
                       Uint8* stream,
                       int    len)
{
    C64 *c64 = (C64 *)thisC64;
//    c64->sid.readMonoSamples((float *)stream,len /  sizeof(float) );      <- this line
}
```

**Comment by dirkwhoffmann** [comment]
I forgot to tell you that flashing only works when the C64 has finished the kernel boot code 🙄. By looking at the code, I've seen that you've figured this out yourself 😎. The real flashing takes place here:

 ```
C64 *c64 = (C64 *)thisC64;
    if(frame_count == 60*4)
    {
        c64->flash(AnyArchive::makeWithFile("roms/FORTAPOC.T64"),0);
    }
    if(frame_count == 60*5)
    {
        c64->keyboard.pressKey(2, 1); //r
    }
```

Because I wasn't aware of this, I only changed the Octopus file name to FORTAPOC in the main routine. When the real flashing took place, it tried to read the Octopus which was no longer there. I think the out of memory error message was a result of a NULL pointer coming back or something like that. 

Now, it works 🥳

<img width="990" alt="Bildschirmfoto 2020-03-13 um 14 12 45" src="https://user-images.githubusercontent.com/12561945/76624100-f157f680-6534-11ea-9441-4a3099f869b0.png">

> I only implemented flash support, did you implement T64 support ?

T64 is a subclass of AnyArchive. You can flash the files in the same way. Out of the box 😎.

**Comment by dirkwhoffmann** [comment]
> Why do you not see the message text for the msg_codes ? Is something broken ?

I temporally changed that during debugging to rule out some issue with NULL char pointers here.

**Comment by mithrendal** [comment]
does sound work on octopus and fort apocalypse in chrome ?

what about the sample size ?
 want.samples = 256; 

I just entered that value because it is a beautiful number ...

**Comment by mithrendal** [comment]
>Because I wasn't aware of this, I only changed the Octopus file name to FORTAPOC in the main routine.

wait ... in sound branch I already deleted that in the main routine ... are you testing the master branch ?

Oh I see I told you to
`git clone https://github.com/dirkwhoffmann/virtualc64web.git 
`
please check out sound branch

`git clone -b sound https://github.com/dirkwhoffmann/virtualc64web.git 64sound
`

**Comment by dirkwhoffmann** [comment]
> please check out the sound branch

Waiting for the compiler to finish 🤤

BTW, the Makefile seems to recompile the whole C64 regardless of the file I change 🤔.

This warning is also strange: 

```
C64/General/basic.cpp:223:2: warning: misleading indentation; statement is not
      part of the previous 'if' [-Wmisleading-indentation]
        if (min > 0 && filesize < min)
        ^
C64/General/basic.cpp:220:5: note: previous statement is here
    if (filesize == -1)
    ^
```

I have no idea what it is complaining about here:

```
bool
checkFileSize(const char *filename, long min, long max)
{
    long filesize = getSizeOfFile(filename);
    
    if (filesize == -1)
        return false;
    
    if (min > 0 && filesize < min)
        return false;

    if (max > 0 && filesize > max)
        return false;

    return true;
}
```

**Comment by mithrendal** [comment]
>This warning is also strange:

I saw this too, I think there is no problem to complain about... maybe emcc wants the returns to be embedded in { }

**Comment by dirkwhoffmann** [comment]
> does sound work on octopus 

Firefox: Yes 😃
Chrome: No 😢
Safari: No 😢

**Comment by dirkwhoffmann** [comment]
Fort Apokalypse has great sound in Firefox. I can watch the computer play 😃:

<img width="907" alt="Bildschirmfoto 2020-03-13 um 15 07 23" src="https://user-images.githubusercontent.com/12561945/76628136-962a0200-653c-11ea-88f2-390a28673c9b.png">

Fullscreen mode seems to be broken in Firefox though (black screen and the mouse can only be moved inside a tiny area in the middle of the screen).

**Comment by mithrendal** [comment]
sound was not playing on browsers which implementing the [new auto playback policy]( https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

Firefox: Yes 😃
Chrome: ??
Safari-Mobile on iPhone: Yes 😎

**Comment by dirkwhoffmann** [comment]
Chrome: 😎 (no autoplay, user has to click)

**Comment by mithrendal** [comment]
Moved all SDL stuff into mainsdl.cpp to keep C64.cpp as clean and uncluttered as possible.  😷 I felt it is important these times ...

**Comment by dirkwhoffmann** [comment]
> to keep C64.cpp as clean and uncluttered as possible. 😷 I felt it is important these times ...

Yes. While working on the emulator, you better carry a mask to protect the code in the next couple of weeks. I know, the medical one are sold out, but you can still get one of those: 

![mask](https://user-images.githubusercontent.com/12561945/76689253-56464600-6634-11ea-9e62-34f4769fb377.jpg)

**Comment by mithrendal** [comment]
Oh no how that one is frightening🙈 !!

**Comment by mithrendal** [comment]
this is too very frightening, no ?

`    void ignoreNextUnderOrOverflow() { /*lastAlignment = mach_absolute_time();*/ }`

I found that in SIDBrigde. I call it a wonder that it plays anyway some sound  ...

I am going to repair this before anybody sees it ...

**Comment by dirkwhoffmann** [comment]
> void ignoreNextUnderOrOverflow() { /*lastAlignment = mach_absolute_time();*/ }

😲 What did you do? This code is part of VirtualC64's sophisticated patent pending ASRA technology (automated sampling rate adjustment 😎).

> I call it a wonder that it plays anyway some sound ...

It only takes effect when the emulator is running for a longer time. It dynamically adjusts the sample rate with the effect that buffer underflows or overflows will be less frequent the longer the emulator runs.

**Comment by dirkwhoffmann** [comment]
> Oh no that one is frightening🙈 !!

These masks helped against the plague, so they must be good. We'll get used to them.

**Comment by mithrendal** [comment]
```
  // Count some sheep to increase precision
    unsigned sheep = 0;
    do {
        jitter = mach_absolute_time() - kernelTargetTime;
        sheep++;
    } while (jitter < 0);
```

sheep counting helps maybe too against the plague 😄
