### ISSUE TITLE
Suggestion: Implement automatic Warp Mode just as the native VirtualC64

### ISSUE THREAD

**Issue by sy2002** [dirkwhoffmann/virtualc64web#33]
My favorite C64 game has `148 blocks`. Loading it in virtualc64web takes ages. Maybe time did mollycoddle me, but in the year 2020 I am just not used to waiting *that long* any more :-)

The native VirtualC64 has a nice feature that turbo boosts the whole C64 while disk accesses are happening. Pretty neat.

**Comment by mithrendal** [comment]
I searched te repo for turbo
`We couldn’t find any code matching 'turbo' in dirkwhoffmann/virtualc64web`

hmm ... how to do this then ? @dirkwhoffmann is it possible to do so ... can you give a hint ?

@sy2002 but I have another idea for speed up things and this is the following point on the goal list 

- storing selected snapshots into local storage ... effectively making those choosen snapshots persistent

the idea is you select a snapshot in the already existing snapshot browser and it asks you whether you want it to be stored right into your own local storage.  
maybe we could make a third row in the snapshot browser for these persisted snapshots ...

that would be the fastest way and the most visual way too ! better than to interact with the awkward non-visual disk dialog ... I mean the first is more like netflix and the latter is like looking for films on your hard disk without the pictures...

**Comment by dirkwhoffmann** [comment]
> is it possible to do so ... can you give a hint ?😬

Keyword is "warp".  There is a function called "setWarpLoad" which enables the auto-warping feature (it activates warp mode if there is activity on the IEC bus connection the drives and deactivates it once the activity is gone). Those functions won't work in VC64web directly, because the sleep logic is different, but you can see in the code what has to be done.

>  persisted snapshots

I never went that road, because the snapshot format is usually changing from release to release. In case of VirtualC64 it only started to stabilize once I worked on vAmiga 😆. The user might think he could build up a persisting long-living library, but all snapshots would have to be erased once the core emulator gets updated.

**Comment by mithrendal** [comment]
>The user might think he could build up a persisting long-living library, but all snapshots would have to be erased once the core emulator gets updated.

Oh yes ... the users will hit me .... 😬 .. we have to display a big red warning ....

**LOCAL STORAGE IS PERSISTENT BUT BE AWARE THAT THIS LOCAL STORAGE MIGHT BE CLEARED WHEN YOU FOR EXAMPLE TELL YOUR BROWSER TO DELETE THE HISTORY OR ALL COOKIES... IN THE END THE PERSISTENCY IS IN THE CONTROL OF THE BROWSER YOU USE**  

different browsers have different policies.. 🙄 I read on some articles

but there could be a solution to this .... exporting of all persistent snapshots into a file to be saved to location specified by the user... and also the importing way ... what you think about it ?

**Comment by dirkwhoffmann** [comment]
> what you think about it ?

I don't really know at the moment. I still have my doubts, but I don't want to stop you doing this. Sometimes, it's only possible to judge a feature once it's there. Only then one could image how it really feels (this is why rapid prototyping exists). 

Another idea would be to implement the persistent snapshot thing in a lightweight fashion, in form of a pause button. When the user hits pause, the emulator could automatically save a snapshot and present it to the user when he comes back to the website.

I don't really know which approach is best at the moment.

**Comment by mithrendal** [comment]
Trust me ... it will be fantastic. 🤤  if not ... we adapt and improve until it is... 😁

**Comment by dirkwhoffmann** [comment]
![trust](https://user-images.githubusercontent.com/12561945/84110239-c9d5d480-aa24-11ea-9561-616723931e4d.jpg)

**Comment by mithrendal** [comment]
**salvator del mundi** 

![grafik](https://user-images.githubusercontent.com/17108995/84115785-ec6ceb00-aa2e-11ea-8cb6-7d55af41c75a.png)

trust me ... I will now free all hostages in choplifter .... and destroy all enemies in fort apocalypse ... and after that I will do the snapshot save dialog ... wait maybe before that I try to get to boulder dash level 4 ...

**Comment by mithrendal** [comment]
>Those functions won't work in VC64web directly, because the sleep logic is different, but you can see in the code what has to be done.

yes true... we are at our old buddy again ... 


```
void draw_one_frame_into_SDL(void *thisC64) 
{
...
  double now = emscripten_get_now();  
 
  double elapsedTimeInSeconds = (now - start_time)/1000.0;
  uint64_t targetFrameCount = (uint64_t)(elapsedTimeInSeconds * 50.125);
 
...
  if(c64->getWarp() == true)
  {
    printf("warping at least 25 cycles at once ...\n");
    int i=25;
    while(c64->getWarp() == true && i>0)
    {
      c64->executeOneFrame();
      i--;
    }
    start_time=now;
    total_executed_frame_count=0;
    targetFrameCount=1;  
  }
...

```

see I implemented the warping at the top of this function ... I had to give him a break every 25 cycles to allow it to draw one frame otherwise the whole UI got very sluggish ... on my old space ship from 2007 ...


![grafik](https://user-images.githubusercontent.com/17108995/85234973-9f671c80-b411-11ea-8851-85517b9b69fc.png)



OMG  all settings enabled ... 🙊


pushed to gh pages ...

**Comment by sy2002** [comment]
@mithrendal Great stuff!

I tested it and it works.

We might want to close this issue.

Or... You might want to investigate further to optimize (but admitably this is very optional and for sure not necessary as I am not sure if it makes it really better):

I guess the warp performance could be better, if you used another mechanism for yielding time back to the cooperative multitasking system. Disclaimer: I am not claiming that it will be better, I am just assuming that it *could* be better :-)

https://emscripten.org/docs/porting/asyncify.html#sleeping-yielding-to-the-event-loop

You could do a loop over the whole warping perfiod and yield back time to the system every here and then.

Maybe one of these two approaches works:

Option #1: Use SDL_Sleep(0) to yield time

Option #2: Use emscripten_sleep(0) to yield time

I do not remember if it is necessary for Option #1 but for Option #2 you need to compile with these switches: 

`-O3 -s ASYNCIFY`

In this case, it is important to set "-O3" otherwise performance will suck.

https://emscripten.org/docs/porting/asyncify.html

You can also try

`-O3 -s ASYNCIFY -s ASYNCIFY_IGNORE_INDIRECT`

to improve performance, but then you might need to have a look at [this article on Medium](https://medium.com/@mirkoholzer/emscripten-sdl2-unreachable-executed-cebd8f034c32).

**Comment by dirkwhoffmann** [comment]
> -O3

-O3 doesn't work. For some reason, the emulator only works with -O2 🙁.
