### ISSUE TITLE
icon library

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#34]
to make the UI more appealing we should use svg icons instead of text  .... I tried some and it looks very nice ...

I really like this .. it is recommended on the bootstrap site... its only 45kb for all the icons ... 

https://useiconic.com/open/

... can we simply use it ?

I am not sure about the license ... seems to be free to use, but I am not an expert...

https://useiconic.com/license/

or should we use another icon library ?

We should have a settings wheel icon a run and pause icon and a fullscreen icon and a keyboard icon. And a camera icon for snapshots. 

Or can we use the icons from the native virtualc64?

**Comment by dirkwhoffmann** [comment]
License seems to be MIT which is fine.

However, I am not sure about compatibility. I went to their GithHub page and clicked "View The Collection": https://useiconic.com/open#icons

In Chrome I can see all icons. In Safari I see noting.
