### ISSUE TITLE
fixed design vs. scrollable

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#36]
I need help in deciding  a major app design point ... 
should the web version have a fixed design like an typical app or be scrollable like a web site?

Currently it has a scrollable design. That is you can scroll vertically to make stuff at the bottom visible on small screens.

but we could make it fixed and give it the full window. Then for exampe we don't need the fullscreen button anymore because it is always fullscreen...

here some impressions...
 
![grafik](https://user-images.githubusercontent.com/17108995/84538594-3802eb80-acf2-11ea-9e02-f23c970dd94d.png)

the controls are also fixed to the bottom and they will not scroll either.. of course they must be made invisible when you don't want to use them.... and visible when you want to use them. Because there is no scolling anymore this could be done with a small icon in the left bottom corner for example. 
And we should put them in a non opaque panel like the keyboard ...

popups would still work as before with the scrollable viewport.
![grafik](https://user-images.githubusercontent.com/17108995/84538943-d5f6b600-acf2-11ea-97ac-5fdc1747f9a2.png)

![grafik](https://user-images.githubusercontent.com/17108995/84539048-08a0ae80-acf3-11ea-9567-c8d3b7b7d7c2.png)

![grafik](https://user-images.githubusercontent.com/17108995/84539329-7b118e80-acf3-11ea-8086-dec1a79d6bd9.png)

 🙋🏿I need advice and your brilliant minds ... to think the pros and cons ...

**Comment by mithrendal** [comment]
![DA8566B1-E31A-4D0D-BB78-6438782AF7E2](https://user-images.githubusercontent.com/17108995/84539773-5d90f480-acf4-11ea-8c84-0f084983335c.png)
![4FB949E1-982F-4C16-96FB-9DFE3F63F0B6](https://user-images.githubusercontent.com/17108995/84539781-5ff34e80-acf4-11ea-9c90-b6e00f038c4b.png)
![552B6B89-DFBC-4E30-8126-A1991022B2B7](https://user-images.githubusercontent.com/17108995/84539785-61247b80-acf4-11ea-9d65-6e24d9cb59bb.png)

**Comment by mithrendal** [comment]
From my feeling the scroll variant is ok for big screens. Because it isso big that ... you don’t have to scroll. On small screens there is a lot scrolling going on but is it any good? I feel it is not ... because you have to constantly care about the scroll positions. 

When we make it fixed then the app has to take care of perfect positioning. This I feel is especially an advantage on tiny screens although it seems to paradox. Because with scrolling you normally get more free space on tiny screens.

**Comment by dirkwhoffmann** [comment]
Did I mention that I am very poor in web stuff 🙄? Anyway. I think a fixed layout is superior. You've already mentioned a lot of reasons for it. I also like the idea of overlays. Is it possible to render overlay with semi-transparency? macOS uses semi-transparent overlays so nicely that it would be cool to have something similar inside the browser. E.g., the app selector (CTRL-TAB) is a very good example how neat looking overlays could be designed (the small notification are good examples, too) . Another question: Is it possible to have smaller GUI elements? I really like the look & feel of SAE (the top menu is very discreet and doesn't distract the user). Nevertheless, I don't like SAE's settings dialogs very much, because it looks somewhat old fashioned.

I'm not sure if it is possible, but in my heart I would like VC64web to look like this 😍:

<img width="579" alt="Bildschirmfoto 2020-06-13 um 08 03 30" src="https://user-images.githubusercontent.com/12561945/84561435-a1afe380-ad4c-11ea-8234-8e213320ee69.png">

**Comment by mithrendal** [comment]
>Did I mention that I am very poor in web stuff 🙄? 

I have everything under control commander ...

>I think a fixed layout is superior.

same as me ... 😬 I hoped for some pros for the existig scrollable design .. well if nobody including me🙊  want the scroll layout anymore then I think we should go for it ... (@sy2002 no pros for the existing layout ? this is your last chance to stop us ?)  


>Is it possible to render overlay with semi-transparency?

sure there are divs and you can set transparency from 0 to 100

>Is it possible to have smaller GUI elements? I really like the look & feel of SAE (the top menu is very discreet and doesn't distract the user). 

In fact I extra made them a little bit bigger as I feared they are too tiny to look at on the big screen and to touch on the small iPhone screen ... I don't like it tooo small .. we are all getting older ... maybe we should make them normal sized 🤔

**Comment by sy2002** [comment]
I like the fixed design a lot! Very clean and user friendly. :-)

**Comment by mithrendal** [comment]
published the first try of the fixed design to gh-pages

**Comment by sy2002** [comment]
Great job. Works like a charm!

But...

Now, that I started working with it, there are two things that came to mind:

1. Make sure that the aspect ration stays correct. Otherwise... Well... Look here:

<img width="1368" alt="grafik" src="https://user-images.githubusercontent.com/6825267/84578762-710d8f80-adc8-11ea-9344-f698d6eb3fa4.png">


2. After a while, the "burger menu" at the top left should fade out / fade away (and maybe fade in, when you move the mouse cursor near it". Maybe this is just my personal taste, but I do not like to see a menu "in the middle of a game":

<img width="846" alt="grafik" src="https://user-images.githubusercontent.com/6825267/84578786-9d291080-adc8-11ea-98f2-2f1ac96badf7.png">

When you consider demos, which use the border, it quickly becomes evident, that you cannot "always" show the menu:

<img width="914" alt="grafik" src="https://user-images.githubusercontent.com/6825267/84578865-4cfe7e00-adc9-11ea-9f7e-002eb6bfe6fd.png">

**Comment by mithrendal** [comment]
>1.Make sure that the aspect ration stays correct.

done  😅

see commit log
```
adapt better to different screen sizes 
try to always keep aspect ratio 320x200, do horizontal and vertical centering
when virtual keyboard comes in no vertical centering to give it more space
adapt on orientchange when rotating landscape/portrait on a phone/tablet
```

pushed ....

**Comment by mithrendal** [comment]
>2.After a while, the "burger menu" at the top left should fade out / fade away (and maybe fade in, when you move the mouse cursor near it".

done 😎 . I altered the thing with the request "fade in when mouse cursor near " because on touch based devices you have no mouse cursor. Therefore I trigger on mouse click or touch start. Intervall for vanishing is 5 seconds...

**Comment by sy2002** [comment]
@mithrendal Just tested it: WOW - this was fast :-) And super high quality implementation. Awesome job!

**Comment by mithrendal** [comment]
<img width="1147" alt="Bildschirmfoto 2020-06-15 um 06 55 34" src="https://user-images.githubusercontent.com/17108995/84620519-8671df00-aed8-11ea-928b-32aaa34d3100.png">

dirk like to have smaller buttons / controls ... so true 

here a comparison with the native GUI

still I don't know how good small controls are for touch devices ... because you have to aim at them with your fingers ...

lets do some work on it !😅

**Comment by mithrendal** [comment]
SAE
<img width="1143" alt="Bildschirmfoto 2020-06-15 um 22 48 36" src="https://user-images.githubusercontent.com/17108995/84704618-68e55980-af5a-11ea-8859-5d373488af1c.png">


the virtual C64 brothers
<img width="1147" alt="Bildschirmfoto 2020-06-15 um 22 42 10" src="https://user-images.githubusercontent.com/17108995/84704061-87972080-af59-11ea-851a-d1637cf0a4d7.png">


>Is it possible to have smaller GUI elements? I really like the look & feel of SAE (the top menu is very discreet and doesn't distract the user).

smaller buttons in place ... also some modifications in order to make it a bit more discreet ... transparency 0.05% ... much better than before, no ?

**Comment by dirkwhoffmann** [comment]
Just tried the latest version. It's a huge step forward! 👍

I really like the menu in the top row and got an idea. Right now, there is a visual gap between the browser elements (menus, tabs etc.) and the emulator controls. If the look and feel of the emulator elements matched the native elements, they would visually melt together (which might be cool looking). However, browser elements look different on different operation systems, so I don't know if this approach is the right one. 

I've notices some minor bugs on Safari. After resizing the window, the options button (the one that needs to be pressed to show the controls) disappeared (even when there was enough space left to the emulator canvas). Furthermore, I got some minor graphics errors when hitting "Pause" and "Run" in a row.

<img width="541" alt="Bildschirmfoto 2020-06-16 um 08 13 38" src="https://user-images.githubusercontent.com/12561945/84738715-b093d180-afaa-11ea-847b-f4c1d54a7795.png">

**Comment by mithrendal** [comment]
>After resizing the window, the options button (the one that needs to be pressed to show the controls) disappeared (even when there was enough space left to the emulator canvas). 

I implemented the following UI logic ... there is a 5 second timer which lets this "burger" button disapppear ... on click or touch somewhere it will be visible again ... and the time starts again. When the top bar is visible the timer will not hide the burger button. 

sy2002 wanted the button to disappear 💁


>I really like the menu in the top row and got an idea.
me too ... but there is a disadvantage with the top position on iOS ... first I had the top bar buttons stick at the very top ... position 0 ... but then the following problem arised in iOS ... when  
you touch at the very top of the display ... although it is button area ... the adress bar comes up...  Therefore I had to place the buttons somewhat away from the dangerous zone ....

**Comment by mithrendal** [comment]
iOS addressbar problem on top navigation

Lets see what the others do here

![59A937F4-2326-4E26-BAEF-0BA6E5E66A20](https://user-images.githubusercontent.com/17108995/84791439-e197f480-aff2-11ea-872b-fbf711aac78e.png)

![ED094C0C-F6FE-4213-A225-9F2448C34847](https://user-images.githubusercontent.com/17108995/84791472-eeb4e380-aff2-11ea-810c-28b245e17209.png)

![BEA1C647-DAF6-4221-812B-48C5E780E455](https://user-images.githubusercontent.com/17108995/84791490-f7a5b500-aff2-11ea-8a03-78777b1fcb3b.png)

**Comment by mithrendal** [comment]
found and fixed the bug 👻

![grafik](https://user-images.githubusercontent.com/17108995/84813596-7a893880-b010-11ea-9df0-52858d1bccd8.png)


next I will try icon only buttons in the nav bar lets see ...

**Comment by mithrendal** [comment]
icons only in the navbar 😎

![grafik](https://user-images.githubusercontent.com/17108995/84817097-c9d16800-b014-11ea-883b-4467e24f04f7.png)

I think it looks nicer ... no ? 🤔

**Comment by dirkwhoffmann** [comment]
> I think it looks nicer ... no ? 🤔

I like it! 👍

The Netflix, Amazon, and Apple pages all look the same in the top row. All show their branding in the top row next to the 🍔 button. What about integrating the VC64web logo there? 😎

**Comment by mithrendal** [comment]
>found and fixed the bug 👻
>![grafik](https://user-images.githubusercontent.com/17108995/84813596-7a893880-b010-11ea-9df0-52858d1bccd8.png)

well that was not true ... but now I found something .. it seems bootstrap can not use tooltips on disabled controls ... this is exactly the problem here ... when pressing run I disable it (to prevent to be called twice) and when pressing halt vice versa... so I think this conflicts with the tooltip mechanism in bootstrap ... look here in he docs ...

`Tooltips for .disabled or disabled elements must be triggered on a wrapper element.`

I only do what they want me to do ... a wrapper element ... a <span> element perhaps  🤔

**Comment by mithrendal** [comment]
>And super high quality implementation. 

@sy2002 just fixed another bug in the activation of the live debug output enabling/disabling ...😫 it just did not work correctly ... @sy2002 what did you say about super high quality ?... you better look at vAmigas code base 😍 to see real high quality ....

**Comment by mithrendal** [comment]
>All show their branding in the top row next to the 🍔 button. What about integrating the VC64web logo there? 😎

![grafik](https://user-images.githubusercontent.com/17108995/84943208-539c3680-b0e4-11ea-89cf-d70a786075ad.png)

![grafik](https://user-images.githubusercontent.com/17108995/84943323-7e868a80-b0e4-11ea-9b05-889704a25b7b.png)

do you think this way with just a label ? the real logo image which you have drawn ... is far to big for the navbar don't you think ? ...

there was a guy which asked me this question ...

>Another question: Is it possible to have smaller GUI elements? I really like the look & feel of SAE (the top menu is very discreet and doesn't distract the user)

**Comment by dirkwhoffmann** [comment]
I meant a logo at the place where all sites present their branding. Something like this (just nicer): 

![banner2](https://user-images.githubusercontent.com/12561945/84982102-3f812500-b136-11ea-838e-742cc193647c.png)

**Comment by mithrendal** [comment]
what should happen when there is no free space ? smaller devices ... should the image be a background graphic with the controls on top then ?

**Comment by dirkwhoffmann** [comment]
> what should happen when there is no free space ?

I'm unsure at the moment. Another idea would be to replicate the VC64mac toolbar. Apple tries to do something similar with iCloud. They try to mimic the look and feel of the MacOS apps as much as possible (at least they did, I don't know if they still do).

**Comment by mithrendal** [comment]
Ok I edited the picture to make the background transparent.... 

![grafik](https://user-images.githubusercontent.com/17108995/85068922-819c7c00-b1b3-11ea-83d7-1c7f2b896278.png)

and I placed it in the center .... hmm I think it looks distracting ... or is it only me ? 


maybe we could make it transparent a bit ...

**Comment by dirkwhoffmann** [comment]
> hmm I think it looks distracting ...

Yes, you are right. That doesn't look good. We better go without it.

**Comment by mithrendal** [comment]
I have put the logo here to the settings dialog ...

![grafik](https://user-images.githubusercontent.com/17108995/85168034-12359380-b26a-11ea-9a35-602790b3eff6.png)


Should we still keep the app label on the top center of the navbar ?
![grafik](https://user-images.githubusercontent.com/17108995/85168417-a273d880-b26a-11ea-89b9-f5d8ccec12a7.png)

I think it is not too shabby there and I still like it, but on the other hand it has also no special value there ... and it would maybe be cleaner to remove it, no ?

**Comment by dirkwhoffmann** [comment]
> but on the other hand it has also no special value there ... and it would maybe be cleaner to remove it, no ?

Yes, I think so, too. It's better to delete it. BTW, the logo looks pretty good inside the settings dialog.
