### ISSUE TITLE
pixel art mode

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#37]
we have a brand new setting 

pixel art on/off 😎✊🏿

![grafik](https://user-images.githubusercontent.com/17108995/85210774-108bce80-b343-11ea-86c9-7600ceae0886.png)

![grafik](https://user-images.githubusercontent.com/17108995/85210814-6791a380-b343-11ea-9a25-57800351dfea.png)

![grafik](https://user-images.githubusercontent.com/17108995/85210896-36fe3980-b344-11ea-92b3-00c0415dd351.png)

![grafik](https://user-images.githubusercontent.com/17108995/85210819-6e201b00-b343-11ea-812d-da1a92aba6a4.png)

firefox ✌️
chrome ? 
safari ... unfortunately it does not work in safari 😭 ... yet .. the canvas does not accept the image-rendering attribute ... maybe a bug  in safari ? in general safari knows this attribute !! on the snapshot canvas elements  for example it works...

here on snapshot ... manually set left most snapshot canvas on safari to image-rendering: crisp-edges; ... which works ... same attribute on emulator canvas shows no effect 😬 .... 
![grafik](https://user-images.githubusercontent.com/17108995/85210975-08cd2980-b345-11ea-85c6-272009d21cdf.png)

I followed this description here https://developer.mozilla.org/en-US/docs/Games/Techniques/Crisp_pixel_art_look

**Comment by mithrendal** [comment]
found this article https://stackoverflow.com/questions/54393847/how-to-stretch-a-webgl-canvas-without-blurring-the-style-image-rendering-does

seems like safari does support image-rendering attribute only at 2d canvas but not yet at webgl canvas ...

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/85211696-fefaf480-b34b-11ea-9cb1-516ff9a71a13.png)

the proof ... safari with 2d software renderer ... look at the last line of log output😄

**Comment by mithrendal** [comment]
they already filed a bug report to the safari developer in january 2019 here https://bugs.webkit.org/show_bug.cgi?id=193895

with the runnable testcase http://jsfiddle.net/greggman/mn9ebgkL/

showing the safari result:
![grafik](https://user-images.githubusercontent.com/17108995/85218678-c20b1e00-b39c-11ea-8acd-94078d7c6fc6.png)

and the firefox result:
![grafik](https://user-images.githubusercontent.com/17108995/85218693-e49d3700-b39c-11ea-9a2d-075ca1e2a1a8.png)

**Comment by dirkwhoffmann** [comment]
Interesting to see that Safari has so many bugs compared to the other browsers. 

I just tried VC64web in Firefox. Toggling between crisp and blurred pixels works perfectly. Very well done!

**Comment by mithrendal** [comment]
> I just tried VC64web in Firefox. 

What about chrome? Is it better than safari?

**Comment by dirkwhoffmann** [comment]
Works perfectly in both Firefox and Chrome. Overall, Chrome seems to be the superior browser, but for some reason, I always use Safari. But I don't know why 🤔.

**Comment by mithrendal** [comment]
I just tried to change the renderer on the fly with a setting ... not SDL which is fine with that but canvas does not allow this. You have to stick to the context "webgl" or "2d" which you initially created all successive calls will be denied by a 
/* this is javascript*/
   canvas.getContext("2d") ---> NULL

since emscripten SDL2 relies on javascript, now when I change on the fly it crashes with  `SDL2.ctx is NULL`  

soooo mean !!!😥

**Comment by mithrendal** [comment]
What about the setting "use accelerated WebGL" with default = true
and the comment that this setting will become active on reload ?
(x) use accelerated WebGL  (becomes active on reload)

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/85232911-409aa680-b403-11ea-8338-56944c564142.png)
