### ISSUE TITLE
building a local stored persistent snapshot library

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#38]
we have now a way to build nice libraries and scroll them in netflix manner ...

here is mine ...

![grafik](https://user-images.githubusercontent.com/17108995/85941856-ccda2b80-b925-11ea-9a0d-e8050c45f2b2.png)

what do you think ? active on gh-pages...

@sy2002 now loading is even more faster and much more convenient ... 

🙊 my favourite games have all black background borders ... without our new persistent snapshot browser I would not have seen that...

**Comment by dirkwhoffmann** [comment]
> what do you think ? active on gh-pages...

Yes. That's all pretty cool 😎. I start liking the idea of individual snapshot caches for different games.

**Comment by mithrendal** [comment]
In Javascript I use the new IndexedDB API for it rather then the Local Storage API. Both storage types are local. The LocalStorage is only meant for settings, hence it accepts only string values... The IndexedDB is also stored locally but is made for high performance ... accepts arrays ... no need to convert to base64 anymore...

I hope browser support is ok... 
I tested 
firefox 👍
safari 👍
safari ios 👍

**Comment by sy2002** [comment]
Cool Stuff! 😎

**Comment by mithrendal** [comment]
When taking a snapshot the javascript prompt in Safari iOS (firefox had no problem) stopped the sound despite I called wasm_run()  ... I have learned that this prompt command is very old style and stoppes everything on a web page ...

so we have it replaced now with a modal dialog ...

![grafik](https://user-images.githubusercontent.com/17108995/85958296-d058cb80-b994-11ea-8d24-e717911d5e05.png)

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/86053353-aa94fa80-ba58-11ea-9b2f-05a260fc6506.png)


blue buttons for the dark mode and explaining text moved to tooltip ...

**Comment by mithrendal** [comment]
Ohh boy 😎 ... now we got overlay buttons for deleting snapshots from the game library ... it has been never easier in an emulator to select and organize your favourite games and game states , no ?


![grafik](https://user-images.githubusercontent.com/17108995/86150794-26954e00-bafe-11ea-86f6-a892806d6d3f.png)

clicking on a snapshot loads it ... clicking on a X deletes it ... without further annoying the user with a dialog ...

**Comment by dirkwhoffmann** [comment]
Very cool!!!
