### ISSUE TITLE
upgraded to progressive web app (PWA)

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#40]
until today we had a normal web app🤗 .. which meant

- that the code was loaded from the webserver (slow)... 
- no offline mode
- no icons when saved to homescreen
- annoying poping up adress bar (on mobile)
- annoying scrolling of the emulator canvas (on mobile)
- annoying swipe gestures (page back and page forward)

now vc64web has been upgraded to a progressive web app and qualifies as a PWA  😎 .... (yes latest technology)

### BEFORE:

![grafik](https://user-images.githubusercontent.com/17108995/86495587-42a52380-bd7a-11ea-9dea-a73e7467487e.png)

### FROM NOW ON:

![grafik](https://user-images.githubusercontent.com/17108995/86495600-55b7f380-bd7a-11ea-95d9-b813883947c8.png)

what does that mean .... 

1. when saved to homescreen app starts instantly from the app cache ... it is not anymore loaded from web server (yes it starts offline like a real app)  (fast)
2. has dirks app icon on the homescreen (mobile only)
3. no scrolling of the emultore canvas anymore (mobile only)
4. no adressbar poping in and distracting the user   (mobile only)
 5. in iOS behaves like a own app ... that means you see it in the taskswitcher as an own app (not a webpage in the safari.app)

we are using now the following local browser storages types ...

- Local Storage for settings and the rom files (limit on iOS 5mb)
- IndexedDB for the persistent snapshots (limit on iOS 1GB)
- Cache Storage for the installation files of the app  (compiled c/c++ wasm code and so on...) (limit on iOS 50MB)

When the app is NOT saved to the iOS home screen (only used in safari) these storages will be deleted automatically if the app has not been used for 7 to 14 days. 

![grafik](https://user-images.githubusercontent.com/17108995/86496094-19859280-bd7c-11ea-838b-b1f7ec2171d7.png)

That means it behaves now like a real app ...😎 well in theory it should ... I have not tested every browser yet🤓 any problems please report them here ...

Ehhm yes ... and the 512x512 icon is missing ... dirk ? do you have one  otherwise a have to upscale from a smaller one ?

**Comment by mithrendal** [comment]
add to homescreen gets the name and the icons from the PWA manifest

![EAD9D923-B7B0-48DF-9166-548229AD6AC2](https://user-images.githubusercontent.com/17108995/86497820-6ae55000-bd83-11ea-8e44-6553c38b4f2c.jpeg)

And here we have a standalone C64 emulator (PWA) app on the home screen of an iPhone ... which doesn’t need the web... only for version updates of the appcode... is that allowed by apple? 🙊
![2F10E879-714C-44BC-AF5E-F4E6FEF2E2AD](https://user-images.githubusercontent.com/17108995/86497833-7afd2f80-bd83-11ea-98f2-c45a9601be0a.jpeg)

**Comment by dirkwhoffmann** [comment]
Wow, that's all very cool 😎!!! I wasn't aware of the fact that PWAs are a way to get around the App Store. VC64web is really progressing fast.

I can provide icons of any size or I can provide the OmniGraffle file. But the round icon doesn't look good on iOS. We need to get to a rectangular shape for the web version. The same will hold for the macOS 11 version, I guess.

**Comment by mithrendal** [comment]
>But the round icon doesn't look good on iOS

icons are here ... https://github.com/dirkwhoffmann/virtualc64web/tree/dev/img

why not replace them ... I am not sooo good at drawing pictures, can you ? ... look the 512x512 one is missing...

I just discovered another big advantage ... the web browser gestures like swipe left for page back navigation is also gone in the installed PWA ... sometimes it happened to me that while I am in the snapshot browser scrolling left in my snapshots that at the end of scrolling (and when I continue to scroll) that the web browser interpretes this as browser back... it is no more with an installed PWA ...

Honestly: we need a virtual touch joystick now !!!

**Comment by mithrendal** [comment]
test candidate desktop chrome ...

click on the vertical three dot menu button at the upper right side ...

![grafik](https://user-images.githubusercontent.com/17108995/86508000-aeb87380-bddc-11ea-8328-ed5ac8672540.png)

choose install

![grafik](https://user-images.githubusercontent.com/17108995/86508030-f0491e80-bddc-11ea-8a6a-bb71114a24eb.png)


![grafik](https://user-images.githubusercontent.com/17108995/86508038-03f48500-bddd-11ea-9d68-e4a5b4809b88.png)

installed into MacOS file system ...

spotlight search ?

![grafik](https://user-images.githubusercontent.com/17108995/86508094-97c65100-bddd-11ea-8677-8a2b4cc407cb.png)


lets start the app ...

![grafik](https://user-images.githubusercontent.com/17108995/86508120-cc3a0d00-bddd-11ea-8448-69d36e1c4e55.png)

it lets me deinstall from the "three dot" menu ... no I don't want to deinstall now


macOS dock ?

![grafik](https://user-images.githubusercontent.com/17108995/86508144-1ae7a700-bdde-11ea-8d5a-46490824a695.png)

Uhh it is edgy !!

**Comment by mithrendal** [comment]
Bug ... iOS does not update the installation automatically 🙈

it updated automatically in chrome ... which makes me think that I have done it right, no ?

I have altered the miami vice color to a neutral light gray and numbered the version cache to 3 in the service worker file `sw.js` which is the file who does all the installation and cache management ...

basically it goes like this ... whenever the pwa app is started it tries to fetch the sw.js file ... if it is the same sw.js file then it loads the app from the app cache.  If it is a new one then the new one deletes the old installation and fetches the new files from the server. This way the update is automatically triggered by a new very small sw.js file.

Chrome behaves exactly like this... but iOS does not automatically update ... 

I have invented a new button to trigger the update manually 

![grafik](https://user-images.githubusercontent.com/17108995/86518275-b275e580-be30-11ea-823e-820f05e7f316.png)

hope it works for iOS ... lets try now ...

**Comment by mithrendal** [comment]
Just used the new invented update button to manually force the update in iOS ... and it works 🤓.

**Comment by sy2002** [comment]
This is amazing stuff! Was not aware of "PWAs" 😀   Great job!

**Comment by mithrendal** [comment]
Apple just published their new AppStore guidelines. 

https://developer.apple.com/app-store/review/guidelines/

As usual they are clarifying on all sorts of restrictions and rules etc. Blablabla. 

And then they mention PWAs in particular 😳... apple insists to call them web browser apps because PWA is a term created by google 🙄...


`Of course, there is always the open Internet and web browser apps to reach all users outside of the App Store`

freedom for PWAs yeah !!!

So apple is fine with emulators 😉 outside the App Store.

**Comment by dirkwhoffmann** [comment]
> Are we now being locked down too ?😩 ... So apple is fine with emulators 😉 outside the App Store.

That's good news. On the other hand, it sound a bit like "Niemand hat vor, eine Mauer zu errichten" 🤔. OK, maybe I am just too suspicious these days 🙁.

**Comment by mithrendal** [comment]
Oh yes ... I accept lockdown measurements for security reasons ... like corona lockdowns 😷... or lockdowns to keep malware/spy software away from my computing devices ... I welcome everything that locks unwanted processes out of my data like photos or mails etc... but in contrary I detest 😤 lockdowns which are solely based on greedy business interests ...

The lockout of emulators from the iOS app store feels a bit like the latter ... and I think it would be fun for example to have that cute scene browser 1.3.2 permanent on an iOS device via the app store ...

PWAs on iOS and the mac are still total freedom✌️ ... yet still more than less ... I think we sleep better when we  believe  what apples frederighi told us once in the interview with gruber 2020 ... that the mac experience it will stay like this 😄...

I already read somewhere that in a future mac OS ... was it big sur ? ... that every mac software has to be signed in order to let macOS recognize when an app has been manipulated by potential malware ... so that it can inform the user about that matter.  But for signing the mac.app you don't have to be part of the developer program ... they will provide free certificates ... easy ... like the compilation of the scene browser 🙊

**Comment by dirkwhoffmann** [comment]
> they will provide free certificates ... very easy ... like the compilation of the scene browser 🙊

Yes, I had the same thought 😂. Hopefully, in Big Sur "it just works" 😬.
