### ISSUE TITLE
Virtual touch joystick 🕹 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#42]
We have now support for a virtual joystick 🕹 
I found the one from @jeromeetienne very good. It worked without any modifications. His [virtualjoystick](https://github.com/jeromeetienne/virtualjoystick.js) is now fully supported. 😎✌️

I told rambo to exercise a testflight and although he is more in favor of the old analoge gear  he said it was a pleasure to fly. 

We made the following photo from the tower...

![642DC955-B6CA-446E-A4B7-5305AECA799C](https://user-images.githubusercontent.com/17108995/86538523-c4ba5700-bef6-11ea-8def-508fca373632.png)

It will be enabled when selecting touch in game port

![8365F8CF-72C9-44CD-A162-02F4D49AA119](https://user-images.githubusercontent.com/17108995/86538826-b2411d00-bef8-11ea-8208-e61877149e20.png)

**Comment by dirkwhoffmann** [comment]
12" C64 tablet with a pencil. Awesome 😎. 

![IMG_3675](https://user-images.githubusercontent.com/12561945/86538822-a9504b80-bef8-11ea-9c97-c67cbd3ab900.JPG)

BTW, I've started to work on VirtualC64 4.0 a couple of days ago. In v4.0, I want to port back a lot of stuff from vAmiga, so both emulator will eventually be closer together, both internally (code base) and externally (GUI).

**Comment by mithrendal** [comment]
nice !! That looks cool ... is it fas enough ?

here I tried the new virtual joystick on desktop with the mouse ... flys ok

![grafik](https://user-images.githubusercontent.com/17108995/86538993-b3267e80-bef9-11ea-9110-71f2d81a4920.png)

**Comment by mithrendal** [comment]
does the touch joystick work with your pencil ?

**Comment by dirkwhoffmann** [comment]
Hmm, it doesn't load any more on the iPad 🤭. It says "Emscripten - Downloading...", but doesn't finish. It loads well in Chrome or Safari.

**Comment by mithrendal** [comment]
I had this too 🥴. Go to ipados setting ... choose safari... scroll down the last item “extended” then choose “website data” the look type in the search field dirk and then delete tge website data by swiping to left

**Comment by dirkwhoffmann** [comment]
Deleting the cached data did the trick, it loads fine now 😎. But I wasn't successful with the game.

I wasn't able to load T64 files on the iPad. When I select a T64 file on the iPad (from the Documents folder like I did with the Roms), nothing happens. Typing "Run" has no effect, too.

CRTs work, but I wasn't able to move PacMan with the new joystick. When I use the pen in the left screen area, I get two white circles, but when I use the pen in the right area, I get red circles. In both cases, PacMan doesn't hear on my commands. Furthermore, using the pen causes the game to freeze from time to time 😲. And there is no sound on the iPad 🙁.

**Comment by mithrendal** [comment]
For enable sound you have to demute the ipad and touch into the emulator canvas. That enables sound.  (We should have an overlay icon for it I guess)

The virtual joystick are effective two. When you touch with the finger in the left half of the screen then this gives the directions ... it shows it with white circles. When you touch the right side ... that tells vc64 the fire 🔥 press ... this is drawn with a red circle

**Comment by mithrendal** [comment]
I got the freezes too now. When enabling the touch joystick... 🙈

**Comment by mithrendal** [comment]
found it the first problem was a copy paste error... that made "port2 touch" selectable ... but it effectively did not create the virtual_joystick componenet... (only when you had before selected port1 and then directly switched to port2 then it was working)

found the second problem ... this was a race condition which led to a null pointer exception and halted the allmighty "draw_one_frame_into_SDL". The problem was that the drop down box selected the touch but it was not created (due to first problem)


both are fixed and pushed to gh-pages ...

**Comment by dirkwhoffmann** [comment]
PacMan works. Woohoo 🥳. Now I know what tablets are made for 😎.

![IMG_6301](https://user-images.githubusercontent.com/12561945/86541230-8e3b0700-bf0b-11ea-9c26-d9aafc51bbe1.JPG)

> For enable sound you have to demute the iPad

How do I demute the iPad? 🙄

**Comment by mithrendal** [comment]
try this https://discussions.apple.com/thread/4239117

**Comment by mithrendal** [comment]
look we got a tiny favicon now ...  do you see it ? Its very small...

![grafik](https://user-images.githubusercontent.com/17108995/86828991-3380e700-c094-11ea-8e65-2f2fed5e95ed.png)

**Comment by mithrendal** [comment]
looking at the pac man screen again ... 

makes me believe that we need now a borderless option in the settings... to be modern and state of the art...  Then the games will even more immersive 


Nobody want's bezels anymore today 😎... Don't really understand why they were so enormous popular back then ??? 

![grafik](https://user-images.githubusercontent.com/17108995/86882817-2219f800-c0f1-11ea-9313-c77cb05c4c84.png)

[Acorn A4 sporting a powerful ARM3 processor](http://www.computinghistory.org.uk/det/22807/Acorn-A4-Laptop/)

```
K/Board 84 keys with arrow keys
CPU ARM 3 (with 4 KB of internal RAM cache)
24 mHz (internal CPU) and 12 mHz (bus)
RAM   4MB
ROM   2 MB
Text: Max : 132 x 30
Graphics: 47 graphic modes, maximum 640 x 480 with LCD screen and up to 1152 x 896 with VGA screen
Screen 14 shades of grey (LCD screen)
Sound: 8 voices (stereo 8 bit)
I/O Ports: VGA, Centronics, RS232 C, stereo sound, Mouse, Keyboard
Drive: 3.5'' disk-drive
OS: RISC OS
Cost: £1395 (2Mb floppy version) up to £1895 (4Mb HD120 version)

Manufacturer: Acorn
Date: 1992
```

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/86963411-c6895200-c164-11ea-9102-fc67034932d8.png)

new small bezels option ( borderless ) ...

iPhone impressions...


OFF



ON

**Comment by mithrendal** [comment]
I tried thinnest bezels possible

With
![512CA33E-EFC4-48BE-8108-E37CE108AC49](https://user-images.githubusercontent.com/17108995/86968990-5632fe80-c16d-11ea-82c5-c10ba35483b0.png)

With thinnest possible
![F16279E5-E2D5-42A6-BFCF-33E6DB497CBB](https://user-images.githubusercontent.com/17108995/86969074-78c51780-c16d-11ea-802d-f5830561fb78.png)



![09C9D524-3C4F-48AD-A293-084A9BACD14A](https://user-images.githubusercontent.com/17108995/86968573-b2e1e980-c16c-11ea-9d91-1a51051523b9.png)
