### ISSUE TITLE
small bezel / wide screen option

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#45]
... continued discussion from #42 

looking at the pac man screen again ... 

makes me believe that we need now a borderless option in the settings... to be modern and state of the art...  Then the games will be even more immersive 

Nobody want's bezels anymore today 😎... Don't really understand why they were so enormous popular back then ??? 

![grafik](https://user-images.githubusercontent.com/17108995/86882817-2219f800-c0f1-11ea-9313-c77cb05c4c84.png)

[Acorn A4 sporting a powerful ARM3 processor](http://www.computinghistory.org.uk/det/22807/Acorn-A4-Laptop/)

```
K/Board 84 keys with arrow keys
CPU ARM 3 (with 4 KB of internal RAM cache)
24 mHz (internal CPU) and 12 mHz (bus)
RAM   4MB
ROM   2 MB
Text: Max : 132 x 30
Graphics: 47 graphic modes, maximum 640 x 480 with LCD screen and up to 1152 x 896 with VGA screen
Screen 14 shades of grey (LCD screen)
Sound: 8 voices (stereo 8 bit)
I/O Ports: VGA, Centronics, RS232 C, stereo sound, Mouse, Keyboard
Drive: 3.5'' disk-drive
OS: RISC OS
Cost: £1395 (2Mb floppy version) up to £1895 (4Mb HD120 version)

Manufacturer: Acorn
Date: 1992
```

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/86963411-c6895200-c164-11ea-9102-fc67034932d8.png)

new small bezels option ( borderless ) ...

iPhone 6S Plus landscape impressions...


OFF
![4E3B9B34-5163-4E94-948C-4045337B52E4](https://user-images.githubusercontent.com/17108995/86965150-634cef00-c167-11ea-9107-e1d2d78040af.png)



ON
![0C2767B5-9A08-4DE1-BE02-3F1955227A82](https://user-images.githubusercontent.com/17108995/86965187-6fd14780-c167-11ea-9687-938aa302ff5b.png)


Question: 
when choosing small bezel aka borderless ... should we completely get rid of the bezels ... look there is still a very small black bezel in fort apocalypse ... 

bezel in fort apocalypse with borderless setting off
![grafik](https://user-images.githubusercontent.com/17108995/86966935-33531b00-c16a-11ea-8090-8fb9812d89ca.png)

bezel in fort apocalypse with borderless setting on
![grafik](https://user-images.githubusercontent.com/17108995/86966779-030b7c80-c16a-11ea-88bc-d8f8bf1b313c.png)

should we go complete borderless then ?

**Comment by mithrendal** [comment]
I tried thinnest bezels possible

With retro bezel
![512CA33E-EFC4-48BE-8108-E37CE108AC49](https://user-images.githubusercontent.com/17108995/86968990-5632fe80-c16d-11ea-82c5-c10ba35483b0.png)

With thinnest bezel possible
![F16279E5-E2D5-42A6-BFCF-33E6DB497CBB](https://user-images.githubusercontent.com/17108995/86969074-78c51780-c16d-11ea-802d-f5830561fb78.png)



![09C9D524-3C4F-48AD-A293-084A9BACD14A](https://user-images.githubusercontent.com/17108995/86968573-b2e1e980-c16c-11ea-9d91-1a51051523b9.png)

**Comment by dirkwhoffmann** [comment]
VC64web goes borderless. Very progressive! BTW, the Acorn laptop needs some cleaning and retrobrighting 😎.

What do you do about games that shrink the border? 🤔 
Another way to go could be the vAmiga approach where size and position of the displayed canvas can be chosen rather freely. However, this would be more complicated to implement from a browser UX point of view. For the moment, I think your approach is very nice and can be kept that way.

**Comment by mithrendal** [comment]
Looking at the landscape iPhone screenshots above ... make it clear that we need another option in the settings .... 
"go cinematic wide screen" ... 

which when set only kicks in when it "can" actually grow wider .... typical in landscape viewing ...

it should not grow taler .... that is when looking in portrait where the height is reduced to keep the original aspect ratio nothing will be changed ...

**Comment by mithrendal** [comment]
New setting in place 😎

Lets try that on iPhone 

![1BE2427B-090C-4EAB-B2DE-C5B4923A7267](https://user-images.githubusercontent.com/17108995/87068788-63f08e80-c216-11ea-9f52-12838ef32d80.png)

Borderless off, wide screen off
![A6E7FBB4-D3BD-4681-9DC7-D535EC0F7E6C](https://user-images.githubusercontent.com/17108995/87068921-99957780-c216-11ea-939f-124b9d1f345e.png)


Borderless on, widescreen off
![0C075B9B-5E57-4573-BD25-1D82BAA604C4](https://user-images.githubusercontent.com/17108995/87068989-b9c53680-c216-11ea-8bd0-e2937b1f9dca.png)


Borderless on, widescreen on
![0E87E799-E187-415A-A203-2509F4306369](https://user-images.githubusercontent.com/17108995/87069036-d3667e00-c216-11ea-983e-31b160a16b57.png)


Loading fort apocalypse now ...

![EA0AF958-D045-4491-9C98-CEC15BED9C1A](https://user-images.githubusercontent.com/17108995/87069112-f133e300-c216-11ea-8369-695e352e36ff.png)

**Comment by dirkwhoffmann** [comment]
> is there a way we can read from a VIC register in the core the current bezel size?

Yes in theory, no in practice. Border size is controlled by two bits in VICII registers $D011 and $D016. $D011 decides whether we get 25 or 24 rows, and $D016 decides whether we get 38 or 40 columns. But some games change these values on the fly which makes it impossible to make a correct decision in all cases. I think it's better to let the user decide how much of the border he wants to see.

Anyway. I like the "borderless" feature 😎.
