### ISSUE TITLE
CustomKeys and ActionScript

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#46]
the user should be able to easily create custom overlay buttons with free positioning and a custom action command ... when clicking such a custom key very long it goes into drag mode where you can position it ... when releasing it after a long press it goes into edit mode where you can alter its appeareance like color, opacity and also its custom action ...

For the action of a custom key I thought of an action script which we can define when the button has been pressed during game play... for example

game example "BlueMax": to throw a bomb (press joystick2 down and fire throws the bomb)
j2fire1|j2down1|delay0.01|j2fire0||j2down0

because throwing a bomb makes the plane loosing height we correct this with
j2up1|delay0.1|j2up0

so the complete ActionScript would look like
ActionScript=j2fire1|j2down1|delay0.01|j2fire0||j2down0|j2up1|delay0.1|j2up0

game example "Spelunker": to fire dynamite ( press d for dynamite on the keyboard...)
ActionScript=keyd

this ActionsScript is very simple only one KeyCommand

because the customkey collection is game dependent ... it will be (automatically) stored and loaded under the title of a snapshot into a separate object store in the indexedDB  ...

**Comment by mithrendal** [comment]
😅I have now all technical HTML5 / javascript pieces together ... which means that I can dynamically create buttons and drag them around and when I click them I can fire some keyboard inputs for the click. In fact HTML5 has all the bits and pieces built in for that job and that is really good news ... I did not need another library or so... 

Now the difficult part begins and that is the refinement of the UI concept 🤔

my current plan is 

that we add a new "+" icon to the top menu bar, with it the user can 
* create a new custom button

holding down the custom button for **a small fraction of a second** makes 
* the buttons action script fire ...

holding down a custom button for **a little longer (lets say at least a half second)** and moving 
* the user simply drags the custom button around .. to a position which is suitable 
* when the user lifts the mouse button or the touch finger dragging stops and buttons stays on the new position 

holding down on a custom button for **one second** (like haptic touch/click)... 
* brings up a dialog with the settings of the custom key 
* where user can define appearance the action script or
* user can choose to delete the button

**Comment by dirkwhoffmann** [comment]
>  I am thrilled to get my hands soon on a working version of this concept

Sounds very cool to me 😎.

**Comment by dirkwhoffmann** [comment]
The question if users will make use of this feature might heavily depend on the ease-of-use. I think it's hard to predict until we have a prototype. 🤤

**Comment by mithrendal** [comment]
>The question if users will make use of this feature might heavily depend on the ease-of-use.

I think we can not underestimate the importance for touchscreen devices which lack a physical keyboard. For some games playing on a touchscreen device is simply a nightmare right now. 🙄

As an example ... think of "raid over moscow" where you have to open the hangar door with F7 function key.

![grafik](https://user-images.githubusercontent.com/17108995/88831017-0923d480-d1cf-11ea-9ac5-bc385ecb5444.png)
```
Turn towards the door and push forward to move towards it. 
Keep tapping the fire button every couple seconds to stay in the air. 
Once you're moving towards the door, hit f7 to open them, Once the 
doors are open, push forward to fly out the doors before they close. 
After that the game gets hard.
```
 
Now on the current implementation with touchscreen you have to switch the keyboard in ... look for  f7 ... hit it ... and hide the keyboard ... to see your plane and whats going on ... and oh you just crashed against the wall of the space station ...😫 ... unplayable no ? 

There are much more games examples where he current implementation is unsufficient ... too meet the goal to make the best of the best of the best of the best 😎

But does the custom overlay buttons pays off for desktop systems too ? 

Yes they do ... some games have just too much special keys to remember ... think of "spelunker" as an example for those games ... 

![grafik](https://user-images.githubusercontent.com/17108995/88832341-f6120400-d1d0-11ea-8db5-deab50e24e7d.png)

```
SPACE  to trigger the Phantom-Blaster
D   to put down a bar of dynamite
F   to fire a flare 
```   

in this case the advantage for desktop systems with a physical keyboard lays in the memorisation of those special functions in the created custom buttons key overlays. 

And this is because we will save them under the same game title as the snapshots. Yes double strike !

That means when you activate a snapshot of a game title it will load automatically the game specific custom keys... this is so cool, no ?

**Comment by dirkwhoffmann** [comment]
It all makes sense what you write and custom overlay buttons seem like a smart idea to me.  

> For some games playing on a touchscreen device is simply a nightmare right now.  

This is true in a very broad sense. E.g., here is my experience with PacMan:

1. Loading the game was pretty easy (once I understood how I can move files from the Mac to my iPad). 
2. The virtual joystick worked (the one with the white and red target zones).
3. About every fifth move, PacMan moved to the wrong direction and got killed by a mean ghost. 🙈
4. Because of that, the game became damn hard to play. 

Point 3 wasn't the fault of the virtual joystick. It did work, even with the ApplePencil. However, the virtual joystick is much more brittle than, let's say, a Competition Pro. It has a considerable failure rate, because the user may not drag it on a straight horizontal or vertical line, or the user starts to drag too early or stops too late. What I want to say is that a C64 games becomes much harder to play compared to the same game on the real machine. All current emulators running on mobile devices suffer from this problem and I don't know if something can be done about it. Surely, it wouldn't make sense to connect a Competition Pro to an iPad, because it would look awkward when doing this in a tram or a bus. Smart overlay buttons could help to some extend (maybe not for PacMan though).

**Comment by dirkwhoffmann** [comment]
> fly out the doors before they close. After that the game gets hard.

Wait. It gets hard *after* exiting the door? 😳 I remember I never managed to even leave the hangar back in the day 😬.

**Comment by dirkwhoffmann** [comment]
> BTW: I love pacman ...

Not to mention his sister... my first true love 😍

<img width="254" alt="Bildschirmfoto 2020-07-30 um 15 41 34" src="https://user-images.githubusercontent.com/12561945/88930172-66755f80-d27b-11ea-8c5f-a5f49ef2cf59.png">

Hmm, maybe a little too much lipstick on this picture 🤔

**Comment by mithrendal** [comment]
Ok I have to stop working on custom keys ... and make a fix for the joystick first .... in order to play mrs. pacman 🤤 ... I will try to patch the code and make the base moving too ...

**Comment by mithrendal** [comment]
new version is😎 online ... plays so much better ... thank you so much dirk for the bug report ... pacmans enemies have a strong touch screen device opponent now 😁

**Comment by mithrendal** [comment]
just pushed a simplified calculation of the moving reference point position ... the first formular worked but was a bit of a mess 🙄

now the new formular is much shorter and behaves quite like the old one ... maybe a bit better ...

**Comment by dirkwhoffmann** [comment]
I can confirm that it's much better now. 😎

However, I still have problems with PacMan. Problems related to the game, not to your implementation. When using the Competition Pro in VC64mac, the following happens:

- Push joystick left -> PacMan starts moving left
- Push joystick down by keeping it left -> PacMan ignores to go down

I think the bad joystick polling code is the reason for the trouble I am having with the iPad and the ApplePencil. This could be fixed in VirtualC64 itself, but I am not sure if it’s a good idea. We could add an option that lets the user choose from „Emulate joystick with 8 directions“ and „Emulate joystick with 4 directions“. In the former case, my use-case above would be translated as:

W -> SW (W = West = Left, SW = South west = Left + Down)

In the latter case it would translate to:

W -> S (W is overwritten by S, because S is more recent)

With some luck, it could make PacMan a whole new experience 🤩 (probably not 😞). On the negative side, the emulated joystick would no longer behave like an original joystick and we would bloat the emulator with more options for which only a handful of people knows what they are meant for. 🤓

**Comment by mithrendal** [comment]
>When using the Competition Pro in VC64mac, the following happens ...

yes same story on vc64web with the Competition Pro ...

    Push joystick left -> PacMan starts moving left
    Push joystick down by keeping it left -> PacMan ignores to go down

on ipad/iphone with virtual touch joystick ... 

    drag left -> PacMan starts moving left
    not lifting the finger and drag a bit down -> PacMan goes down when it reaches the way down ...

🤔 the virtual touch joystick works somehow better together with the polling code of the devs from 1983 ?? I guess it must have to do with how I translate the touch events to joystick movements 😎, no ?

```
 function handle_touch(portnr)
{    
    if(v_joystick == null || v_fire == null)
        return;
    try {
        var new_touch_cmd_x = "";
        if(v_joystick.right())
        {
            new_touch_cmd_x = "PULL_RIGHT";
        }
        else if(v_joystick.left())
        {
            new_touch_cmd_x = "PULL_LEFT";
        }
        else
        {
            new_touch_cmd_x = "RELEASE_X";
        }

        var new_touch_cmd_y = "";
        if(v_joystick.up())
        {
            new_touch_cmd_y = "PULL_UP";
        }
        else if(v_joystick.down())
        {
            new_touch_cmd_y = "PULL_DOWN";
        }
        else
        {
            new_touch_cmd_y ="RELEASE_Y";
        }
        var new_fire = (v_fire._pressed?"PRESS_FIRE":"RELEASE_FIRE");
        var new_touch_cmd = portnr + new_touch_cmd_x + new_touch_cmd_y + new_fire;
        if( last_touch_cmd != new_touch_cmd)
        {
            last_touch_cmd = new_touch_cmd;
            wasm_joystick(portnr+new_touch_cmd_x);
            wasm_joystick(portnr+new_touch_cmd_y);
            wasm_joystick(portnr+new_fire);
        }
    } catch (error) {
        console.error("error while handle_touch: "+ error);        
    }
}

```

**Comment by dirkwhoffmann** [comment]
> the miracle is ... why does pac man continue to go left when I swipe down ??? 

It's the way how the game interprets the joystick bit patterns coming from the CIA register. The "DOWN bit" is there, but the game ignored it when the "LEFT bit" is already set.

> works somehow better together with the polling code of the devs from 198

This is game dependent. For Fort Apokalypse, the code needs to be as it is.

**Comment by mithrendal** [comment]
Ok know the solution of the miracle ... I observated why it worked quite well on iPhone and I mastered to play pacman with the competition pro !!

read on ...

observations on iphone with live debug on ...


the "down drag" virtual joystick  movement was interpreted as down "only" because the reference point has already followed the finger 😎 


now with the competetion pro ...

how to make pac man dont stop to run left and go down immediately when pac man is at the corner ? or how the devs meant to play pac man with the real joystick back then ?

   * Push joystick left -> PacMan starts moving left
   * Push joystick down by keeping it left and then releasing left by keeping down -> now PacMan does what we want him to do ... he continues to go left and when reaching the corner it goes down ...

**Comment by dirkwhoffmann** [comment]
> how the devs meant to play pac man with the real joystick back then

Or maybe it was like this... once upon a time at Atari labs:

Developer: "Boss, the joystick code is screwed up. Can I fix it?"
Boss: "The games was due yesterday. Ship it."

No? 🤔

**Comment by mithrendal** [comment]
yes !! It was most likely like this ... 🙄

**Comment by mithrendal** [comment]
Hi team we did reached "phase1" into the land of a freely customizable UI  😎


The result is just awesome ... here you see me playing spelunker ... do you see the three buttons in the right upper corner ? These are custom buttons ...
defined by the user ... 

what is in "phase 1" included ?

* automatic game specific persistancy
* can set the label text of the button
* can set a character which will fire when button is pressed 
* can add as much buttons as you like to
* can delete buttons
* can move buttons to another position. When move operation is ended the position will be automatically persisted

**Comment by dirkwhoffmann** [comment]
<img width="682" alt="Bildschirmfoto 2020-08-11 um 11 54 19" src="https://user-images.githubusercontent.com/12561945/89884439-d82da180-dbc9-11ea-9bfa-463e4fff9c50.png">

Works great with Safari 🥳.

Emojis are a nice idea to label the button (the dynamite button is really cool in Spelunker 😎).

**Comment by dirkwhoffmann** [comment]
I really like the translucent style of the buttons 😎. Looks much much better than the usual stuff we see in browsers.

Just an idea: Why not rebuild the VirtualC64mac toolbar with translucent buttons? These buttons could form the top row  just as the title bar in an macOS window (with the additional burger icon to show and hide all controls). The custom buttons (Spelunker dynamite etc.) could be the second row. Maybe an option could be added to place the custom buttons left, right, etc. (like the option in macOS to place the dock at different screen locations).

**Comment by mithrendal** [comment]
Behind the scenes ...  (in picture you see the firefox web space inspector)

![grafik](https://user-images.githubusercontent.com/17108995/89930306-d6380280-dc0a-11ea-83a7-72cda27bed8d.png)

we have now 3 tables ... or in browser javascript language they say object stores ...

* one for the app title 
* one for all snapshots (each app has its own set of snapshots)
* and one for the custom buttons for the apps (each app has its own set of buttons)

the custom buttons for one individual app title are stored in a JSON (Javascript Object Notation) string ... which is serialized from a array of custom button entries ... 

when a snap shot is deleted its app entry will be deleted too ... snapshots are weak entities ... 

for the custom buttons I decided to not delete them when all snapshots of an app title (and therefore the app title itself too ) is deleted ... so custom buttons are a like strong entities which can live forever... this is so because they are also matched against a floppy or .crt file where you will never might maybe never take a snapshot ... When you insert a game make some buttons and just close the browser the next time you insert the disk or .crt again the buttons will be just there ... This is very handy, no ?


>I really like the translucent style of the buttons 😎. Looks much much better than the usual stuff we see in browsers.

yes ... dirk ... we have a cool thing now ... I can't wait to make the vAmiga... But the better we do the vc64WE the better the vAmigaWE will be ...

but before I still like to some things
*action script 
*and most importantly clean up ... I spent all the time on implementing to get the last features running (persistent snaphots ... custom keys) ... some refactoring and separation of code is now necessary I think 🙈...

>Why not rebuild the VirtualC64mac toolbar with translucent buttons? These buttons could form the top row just as the title bar in an macOS window ...

yes cool idea ... we can replic all of these buttons (even the icons of the current navbar like pause run take snapshot ...) we can do it with the power of ActionScript™

**Comment by dirkwhoffmann** [comment]
> yes cool idea ... we can replic all of these buttons (even the icons of the current navbar like pause run take snapshot ...)

Yes, I think that's gonna be cool. In addition to awesome looking icons, the desktop and the web version will then have a similar appearance and can be immediately recognized as being brothers (or sisters? 🤔).

**Comment by mithrendal** [comment]
>recognized as being brothers (or sisters? 🤔).

you mean like iOS and macOS ?🖖🏼

**Comment by mithrendal** [comment]
some small optical tweak ... delete button red and left aligned now 😎

![delete](https://user-images.githubusercontent.com/17108995/90037360-6a19d500-dcc4-11ea-929d-a1f17e67c894.png)

**Comment by mithrendal** [comment]
This seems to be like an early idea of ghost busters ...

Ghost 👻 is approaching from the left
![E5A8E1DA-2C3F-4E65-B955-28C2A9442FB9](https://user-images.githubusercontent.com/17108995/90057684-0b168900-dce1-11ea-8020-4739e8917739.png)

... but Rambo is cautious ... he spots it and presses the ghost custom button ... which activates his phantom blaster ...

![9A9C2208-92A9-43CA-A9D1-C58F3C7FA56C](https://user-images.githubusercontent.com/17108995/90057716-15388780-dce1-11ea-9686-34e1a237d0f4.png)

**Comment by mithrendal** [comment]
raid over moscow. Rambo just hit the space stations door opener button can you spot it?


![29E91D94-D780-45F3-B4B2-273EC1C77E07](https://user-images.githubusercontent.com/17108995/90062148-867b3900-dce7-11ea-94a2-1cffa133927f.png)

**Comment by dirkwhoffmann** [comment]
I remember to have played Spelunker once, hundreds of years ago. I never understood what I was supposed to do, because I didn't know anything about the keyboard stuff. And there were no action buttons on my screen back in the day.

**Comment by mithrendal** [comment]
done ...
