### ISSUE TITLE
should we interface to the c64 scene database ?

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#49]
there is an iPhone app called C64 Scene 1.3.2 at https://csdb.dk/release/?id=171112

(I downloaded the source code, built it in xcode and deployed it on iPhone...)

![B2DB7DBD-153A-4BA8-9591-30A490F2F011](https://user-images.githubusercontent.com/17108995/90155601-cf84c900-dd8b-11ea-82d7-b6481845538e.png)

![E626AAAA-02CC-4542-9575-7DAE2AFDB478](https://user-images.githubusercontent.com/17108995/90155626-d6abd700-dd8b-11ea-98b9-b4fde0d591ea.png)

![712E2F74-3A51-4A22-B804-6180FC9D1D1A](https://user-images.githubusercontent.com/17108995/90155689-e5928980-dd8b-11ea-9e4c-a74864673f39.png)

![A738C241-A7C6-409C-A6BE-4F46E231E0F1](https://user-images.githubusercontent.com/17108995/90156175-736e7480-dd8c-11ea-97ce-6b060ee53261.png)

which is a visual browser for iOS for all the stuff inside the csdb ... new demos are comming in regulary from the sceners ...

with it one can browse for the latest releases, the latest additions, top demos, etc ... and directly play them without to hassle with downloading files ....

I took a look into their source code ...

the source code points to a webservice for the list of different categories 

https://csdb.dk/webservice/?type=latestrel
for latest releases

or

http://csdb.dk/webservice/?type=chart&ctype=release&subtype=2
for top demos 

and more ...

strangely the download link is not directly provided in one list entry ... but an id

the ids in the list can be put into here to get https://csdb.dk/release/?id=123456 
to get the download link of an entry ...  (maybe there is also a simpler way for example an webservice to resolve the link with a webservice, I still have to dig deeper into the soure code ...)

But before looking deeper into this thing...

The question is: is it a good idea that we implement such an browser interface into vc64WE too ?

**Comment by mithrendal** [comment]
Oh 😯this thing also supports loading zip files wich contain multiple floppies. 

This demo requests another floppy

![690015BD-B257-420F-B930-A47B2BCA4570](https://user-images.githubusercontent.com/17108995/90164213-64d98a80-dd97-11ea-8f51-ec37d08e3e6b.png)


the scene browser app lets you hot swap them while running the demo

![EB3E838C-B60B-4297-A2F6-47821B0FED41](https://user-images.githubusercontent.com/17108995/90164043-3065ce80-dd97-11ea-8996-d97b0f866817.png)

**Comment by dirkwhoffmann** [comment]
> The question is: is it a good idea that we implement such an browser interface into vc64WE too ?

This rises the question of target audience. I guess the main audience of web emulators are casual users who want to travel back in time for an hour or so, gamers who want to play a round of Mrs. PacMan (😍), or people who want to watch a demo. Web emulators are especially great for the latter group, because there are no issue with input devices. Bottom line: I think it would be great to connect to this web service.

Maybe it's also time to think about the start page of the emulator, because the design is a major decision factor for the user to stay or leave. Maybe we could show four translucent buttons with Rom images on the top page if no Roms are installed and tell the user that he can use them as drag and drop targets?  In addition, some interface element to the web service could be shown. I.e., the user should immediately see that he can browse a demo collection. Browsing should be possible without having the Roms installed. This increases the motivation to add Roms once a cool looking demo has been found. 

"C64 Scene 1.3.2" is not available from the App Store, is it?

**Comment by mithrendal** [comment]
Yes good ideas...

>"C64 Scene 1.3.2" is not available from the App Store, is it?

Of course not as it violates the app store rules e.g. no code side loading from network allowed... and every emulator like thing pushed to the store must have all code embedded I think...

I browsed a lot of cool stuff in the meantime... and also a lot of crap to be honest... Every 7 days the free provisioning certificate will expire and the scene browser has to be deployed again 🙄

Another thing which came to my mind was that when we do this it will have also use for vAmiga ?

If not we maybe better park this idea here for a while and doing in the meantime some other stuff ActionScript and vAmiga?

**Comment by dirkwhoffmann** [comment]
> Another thing which came to my mind was that when we do this it will have also use for vAmiga ?

But csbd.dk only has C64 stuff.

**Comment by mithrendal** [comment]
Refering to the strict app store rules...

They are seeing this as a defense line against malware I guess. PWAs are ok as the HTML5 WASM layer serves as security sandboxing...

I think we first do the translucent ROM drop zomes ... then Action Script 😍 and later we decide again vAmiga or the SceneBrowser interface

**Comment by dirkwhoffmann** [comment]
> I think we first do the translucent ROM drop zones ... then Action Script 😍 and later we decide again vAmiga or the SceneBrowser interface

That's the way to go. Bring it on 😎.

**Comment by dirkwhoffmann** [comment]
> Maybe with an option to drag the mega64 roms in it

Supporting the Mega64 Roms as a fallback is a very good idea, I think. Maybe we can ask the Mega65 team to place the Roms at a fixed location and grab the latest and greatest revisions on-the-fly?

**Comment by mithrendal** [comment]
> Roms at a fixed location...

From JavaScript we could easily fetch them from there but when they update... we have no guarantee that they will work ... because it is not tested ... no? Where are the files hosted ? Do you know a link?

**Comment by dirkwhoffmann** [comment]
They host the sources here: 

https://github.com/MEGA65/open-roms

**Comment by mithrendal** [comment]
Cool this is already a pretty fixed location 😄

Look at the bin folder I guess we need the three generic roms. And I have to patch the core in order to start it up with only three roms no?

**Comment by dirkwhoffmann** [comment]
>  And I have to patch the core in order to start it up with only three roms no?

😱 OMG, I forgot about this. The v4.0 core can already launch with 3 Roms, only, but the v3.x core can't. Unfortunately, the v4.0 core is not ready for deployment, yet. 

But we could still offer an option that grabs the OpenRoms from the GitHub repo. To run the emulator, the user has to add a drive Rom though. Once the v4.0 core is ready, the emulator could start automatically when the OpenRoms are installed.

**Comment by mithrendal** [comment]
That is a good plan ... let’s do it 👍🏻

**Comment by mithrendal** [comment]
well AcionScript support is nearly done ... we can look forward into the scene browser interface ... 

the first thing we have to do is to check whether they support CORS ...

**Comment by dirkwhoffmann** [comment]
> the first thing we have to do is to check whether they support CORS ...

The C64 Demo scene browser doesn't require CORS, because it's a native iOS app, right?

**Comment by mithrendal** [comment]
Yes.

**Comment by mithrendal** [comment]
the game goes like this ... when data is loaded from an URL via javascript in the browser then the browser adds the header origin to the request ... the origin from which the javascript was loaded...

when the response comes in the browser looks for the access-control-allow-origin: header parameter

if that one matches the orign it lets the javascript receive the data ...

I mean it is not that some websites intentional want not to share their data ... its only they are sometimes not aware of CORS and the header is missing ... and therefore javascript can not load data from their side ... 

for regular desktop apps there is no such security layer ...

I will check now ...

**Comment by dirkwhoffmann** [comment]
> I will check now ...

😬 Tension rising...

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/95023009-da1c5a00-067a-11eb-9a69-e1fcb2acb56f.png)

I am using an action button for this of course 😎

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/95023153-aa218680-067b-11eb-9a63-4e5ab4a20e1d.png)

😭

**Comment by mithrendal** [comment]
I will try to load choplifter from www.c64games.de ...

hang on ...

**Comment by mithrendal** [comment]
situation is no better for AmigaScene Browser ...

look here are the data URLs from https://demozoo.org/parties/3770/#competition_15084  which @emoon told us 

![grafik](https://user-images.githubusercontent.com/17108995/95023889-e0610500-067f-11eb-9439-e23596dc07f2.png)

it redirects our secure https  to insecure ftp protocol 🙄 ... this is really oldschool ... in that case CORS fails completely because ftp does definitely not know about the CORS web browser policy ...

I did not excpect so many webservers not configured correctly ... Whats the use of a https secured website in the front when everything behind is insecure ...🙄

**Comment by mithrendal** [comment]
hmm ... we could register an account in csdb.dk to ask them to set the http response header `Access-Control-Allow-Origin: *` in all their http responses ... what do you think ?

**Comment by dirkwhoffmann** [comment]
> hmm ... we could register an account in csdb.dk to ask them to set the http response header

At first glance, this seems to be the onliest solution right now.

> and all those other sites 😭

Hmm, yes. Maybe the approach is a dead end in general, even if a specific site such as csdb.dk would enable CORS. Even worse, they could revert the setting any time. We'll loose control over what we do if we go down down this road.

**Comment by mithrendal** [comment]
>this seems to be the onliest solution right now.

there is another solution to the problem ... a CORS poxy ...

instead of directly fetch a resource from https://csdb.dk/blablabl...

vc64web could fetch for example from

https://crossorigin.me/https://csdb.dk/blablabl...

which itself sets the allow header and effectively tunnels the CORS request ...  

here are those proxies 

https://alternative.tips/crossorigin-me-alternatives-47462


but of course this is some sort of a man in the middle by design ... I am not so happy with this solution as it clearly concerns the users privacy ...

>Even worse, they could revert the setting any time. We'll loose control over what we do if we go down down this road.

yes you have it already in mind ... the proxy service could also break anytime ... 

we could do a round-robin over the 5 crossme alternatives ... 🤓... which would also help a a "very very little" bit for more privacy

**Comment by mithrendal** [comment]
this CORS proxy really works ... but I think they will always come and go ...

Idea: we could make an option in the settings ... CORS-proxy:   and there we can let the user enter the proxy he likes ... 

```
js:

var load_csdb = function (rom_url){
        var oReq = new XMLHttpRequest();
        oReq.open("GET", rom_url, true);
        oReq.responseType = "arraybuffer";

        oReq.onload = function(oEvent) {
            var arrayBuffer = oReq.response;
            var byteArray = new Uint8Array(arrayBuffer);
            var rom_url_path = rom_url.split('/');
            var rom_name = rom_url_path[rom_url_path.length-1];

            var romtype = wasm_loadfile(rom_name, byteArray, byteArray.byteLength);
            if(romtype != "")
            {
                localStorage.setItem(romtype+".bin", ToBase64(byteArray));
                load_roms(false);
            }
        };
        oReq.send();  
    }

    load_csdb('https://cors-anywhere.herokuapp.com/https://csdb.dk/getinternalfile.php/122087/Blood.d64');
```

**Comment by mithrendal** [comment]
this proxy thing surely would work and with a setting we give the power into the hands of the user ... but it still is not the best approach... the best would be when CSDb would add the `Access-Control-Allow-Origin: * `header to their http-responses

I just send an registration request ... and wrote the following ..

```
I am developing vc64web (1) and interested in connecting the web based emulator to the CSDb like the existing SceneBrowser iPhoneApp (2). I think that would be really cool as it would be possible for all of us to browse the scene-db and start cool stuff directly from the browser without downloading ... Our source code is on github, you will find the documentation of the planned feature here (3). We have currently the need that you at csdb add an http reponse header which would enable the vc64web to fetch the entries in csdb from javascript directly ... more details see the issue (3) 
best regards

(1) https://dirkwhoffmann.github.io/virtualc64web/
(2) https://csdb.dk/release/?id=171112
(3) https://github.com/dirkwhoffmann/virtualc64web/issues/49

```

**Comment by mithrendal** [comment]
after we did some investigations into the feasability of the data fetch ...  

I am back today at the drawing board ... to think of a component which would be usable for both vc64web and vAmigaWeb and also for different demo database sites ... 

the idea is to setup a "scene browser" interface component - which is flexible and highly reusable 
 
the user interface:
* it consist of a list of feeds
* each feed list will consist out of items which have a teaser pic a short text (and a long text which is still hidden at this point)
* when clicking on a feed list item it shows its details (also the long text) and the user can start the items program

the feed interface:
* for each website like http://csdb.dk or https://demozoo.org we will set up a data-collector which will collect the data from their site and which will provide a standard interface to the vc64web or vAmigaweb which can transform this into the user interface

**Comment by dirkwhoffmann** [comment]
If they enable CORS, it would be the best solution for us. Otherwise, we are really running in a conflict with the complexity of the emulator versus the goal of the target audience. Among 100 users, maybe 1 or 2 know what CORS is and are willing to configure the emulator appropriately. I think everything we do should work out of the box.

If they don't enable CORS, we could go the SAE way and put some selected demos into the GitHub repo next to the emulator (I guess there are many free demos around). The user could select one of those or he could add other demos manually. Of course it would be much nicer to have access to a giant database.

**Comment by mithrendal** [comment]
hmm maybe we could do it as follows  ... 

we set up a generic scene browser component and decouple the data fetch code into data-collectors 

>If they don't enable CORS, we could go the SAE way and put some selected demos into the GitHub repo next to the emulator (I guess there are many free demos around).

in this case we write only a data-collector for our own collection at https://dirkwhoffmann.github.io/virtualc64web/ 

maybe we can turn the current snapshot browser into such a component and separate the existing snapshot reading code into such a data-collector. In other words we could generalize the current code of the snapshot browser and turn it into a flexible media selection component ... 🤔

**Comment by dirkwhoffmann** [comment]
Sounds like a good idea. As long as CORS is enabled, the whole demo library can be accessed. If CORS is disabled, a small offline library is used as fallback solution. 👍

**Comment by mithrendal** [comment]
Short update... I have got mail from the csdb admin. They want to support us. I just wrote a mail with what we need. 

@dirkwhoffmann can I send you the mail conversation  ? Which adress should I use? I am not sure whether they want the mail conversation  posted here to the public.

**Comment by dirkwhoffmann** [comment]
> They want to support us

Seems to be our lucky day 🥳.

> can I send you the mail conversation ? 

Please use my work address for now: dirk.hoffmann hs.karlsruhe.de

**Comment by mithrendal** [comment]
csdb.dk just allows the CORS with our domain ... see here this test request

![grafik](https://user-images.githubusercontent.com/17108995/95660278-0c203700-0b27-11eb-8ac1-5215f09ebbfd.png)

dirk ... I added you as CC to in my answer mail to the friendly guys at csdb.dk

**Comment by dirkwhoffmann** [comment]
> I added you as CC to in my answer mail to the friendly guys at csdb.dk

Didn't get anything 😢. Maybe it's better if you use my personal Email. But I cannot post it here, because it wouldn't be personal any more 🤔.

**Comment by mithrendal** [comment]
Write me to this 

![A2F0A66D-35F7-4306-9F3E-8FB52ECF51A4](https://user-images.githubusercontent.com/17108995/95661248-2873a200-0b2e-11eb-91a3-133dbb0db38e.jpeg)

**Comment by dirkwhoffmann** [comment]
> Write me to this

OK. Done. 🤓

**Comment by mithrendal** [comment]
OK ... I resent it to your personal mail did you get it ?

**Comment by dirkwhoffmann** [comment]
> did you get it ?

Just received it. This can become a really cool project I think 😎.

**Comment by mithrendal** [comment]
I am in the midst of refactoring the current snapshot browser ... 🙈 I break everything ... and separate the UI code from the specific datafetch code ... so that we can connect different datasources to the current snapshot browser

it will just be the browser in future 😜  we will place a option control like this in the header of the snapshot browser

![grafik](https://user-images.githubusercontent.com/17108995/95661719-c4eb7380-0b31-11eb-86dd-0be688b81b3a.png)

that way the user can easily switch to different sources .... first option will be "snapshots" the other will be "CSDb.dk", and we could add even more ...🤓

**Comment by mithrendal** [comment]
code has been successfully refactored to connect different data sources ... 

we have now separated the data loading stuff for the snapshots into a data-collector class

I have stretched the modal window from large to extra large ... as we might need the extra space ...

![grafik](https://user-images.githubusercontent.com/17108995/95663580-b35d9800-0b40-11eb-9bba-af4b715d583c.png)

now we only have to write another data-collector class for csdb.dk   ... 😎

**Comment by mithrendal** [comment]
first contact ... vs64web loads "latest releases" into the snapshot / db browser component ... 🤤 🤤 🤤 

![grafik](https://user-images.githubusercontent.com/17108995/95686598-17469600-0bff-11eb-8470-927df945d346.png)


🤤 🤤 🤤 more ... more of this

**Comment by mithrendal** [comment]
connection completed ... 😎

![grafik](https://user-images.githubusercontent.com/17108995/95741101-f8431500-0c8d-11eb-8a60-fbdccbebf258.png)

published to gh-pages ... so the version is online ...  

we currentIy have only connected one feed : top demos 🤤

thanks to the friendly guys at CSDb.dk 😍

in the coming days we can polish and fine tune this ...

**Comment by mithrendal** [comment]
There are still some problems

First: in order to auto run with basic commands we have to reset to switch into basic before we mount another demo. Therefore  I do an explicit reset shortly before  the user can press the mount button. When pressing while in reset procedure the mounting fails. 🙈

Second problem: in the browser when switching between snapshots and csdb too fast the result get mixed 🙈

**Comment by mithrendal** [comment]
I am playing with the above timing ... strange the reset on original roms is much slower than on open roms

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/95915719-ddfd5a00-0da7-11eb-9934-8f620b7715fd.png)

we have three feeds (rows) now

top one filer demos
top demos 
and latest additions

**Comment by mithrendal** [comment]
I just mounted the top 1 uncensored demo ... wow that one is really cool 😍

I discovered two things ...
1. warp mode must be turned off because it loads asynchronously in the background while demo is running ... 

2. because these are floppies ... we need a floppy rom installed ... but until now vc64web inserts disk as if there sky is the limit ... and you wonder why it does not load ...

so time for some validation messages 😎 


![grafik](https://user-images.githubusercontent.com/17108995/96030479-56bdee00-0e5c-11eb-8cc9-c860fae9b878.png)


so the new release warns the user before a d64 or g64 files is to be inserted

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/96179972-0749f180-0f32-11eb-9767-d81d2582f4bb.png)

label added to each entry 😎

we should provide an info overlay button for each entry, no ?

**Comment by dirkwhoffmann** [comment]
Worked pretty well so far 😎

<img width="1103" alt="Bildschirmfoto 2020-10-16 um 12 42 12" src="https://user-images.githubusercontent.com/12561945/96251077-356e1680-0fb0-11eb-9923-abf3c2129630.png">

I had a small with one of the demos though. I don't exactly remember which one I selected, but according to the error messages, I guess it was "Survival Messenger Adventure". First, this came up:

<img width="442" alt="Bildschirmfoto 2020-10-16 um 12 43 31" src="https://user-images.githubusercontent.com/12561945/96251235-749c6780-0fb0-11eb-9993-52c1060f1923.png">

Afterwards, it proceeded as expected: 

<img width="495" alt="Bildschirmfoto 2020-10-16 um 12 43 47" src="https://user-images.githubusercontent.com/12561945/96251284-83831a00-0fb0-11eb-92ba-9b753a8fedee.png">

I was not able to verify if the demo was working, because I had no drive Rom installed.

**Comment by mithrendal** [comment]
>I had a small with one of the demos though.
found it thx for reporting bro 👍 ... fixed it ... should work now 😎 fixed another one too where the file names got strange names when spaces where used ...

darkmode is now the default

I spent some thinking into how to handle caching ... before was purley aggressive ... every resource which vc64web loaded was cached ...indefinitly 

we have to find a good trade off between offline expierience, speed and at the same time presenting new stuff to the user ...

I have change it now to the following strategy ... I hope it suits much better
* vc64web files itself and csdb feed entry image files and the downloaded demos are currently cached 
* the feed rows 'top demos' and so on, are not put into the browser cache anymore ... we only load it once when the app is started ... when we start it the next time it has to load all feeds again from the CSDb webserver ...  this way the user sees new releases, additions and demos everytime vc64web is started or reloaded  ... any thoughts ? Maybe we should add an in-app refresh button too ?


 
no sticky persistent caching for csdb feeds anymore, refresh when app is reloaded in browser ...

**Comment by mithrendal** [comment]
optimised the snapshot/ csdb browser communication with the collector ...

it collector supports now the method `needs_reload()` with it the collector can signal the browser that it does not need a reload and therefore the browser needs not to refresh ....

with that feature ... scrolling positions are preserved now when leaving the browser (for example when starting a demo) ... when coming back to the browser the scroll positions of each row are in the state when the user left it  (also it is insanly fast now 😎)

**Comment by mithrendal** [comment]
added decent title rows in light gray ... 

![grafik](https://user-images.githubusercontent.com/17108995/96302365-fc0dc900-0ff8-11eb-9662-07c50a4dc2f7.png)

**Comment by mithrendal** [comment]
now that it works really nicely ... I am going crazy and turned the booster on and added additional csdb rows ... latest additions ... top graphics ... top music  ... top everything ... and so on 😎

OMG this is really huge and there are still more feeds to connect 😳  ... I bet  this is for sure more content than netflix has 🤓

**Comment by mithrendal** [comment]
we just got a detail view now !!! 😎

![grafik](https://user-images.githubusercontent.com/17108995/96374004-5d0bdd00-1170-11eb-853a-e5ee59348720.png)

also visual appeareance of the browser has been improved ... more gaps ... smaller teaser images ...

**Comment by dirkwhoffmann** [comment]
Yesterday, I've got a typing error in Safari (one key press was not recognized).

<img width="1034" alt="Bildschirmfoto 2020-10-18 um 15 24 49" src="https://user-images.githubusercontent.com/12561945/96704255-2a422e80-1394-11eb-8901-c8001faf6fc6.png">

I think the best solution will be to move the auto-typing stuff from the GUI side into the emulator core. I'll see what I can do...

There is still this BEEP Rocklobster vAmiga bug which drives me crazy 😖...

**Comment by mithrendal** [comment]
currently the emitting code is located in js/vc64_ui.js

```
emit_string(['Enter','l','o','a', 'd','"','*','"',',','8',',', '1', 'Enter']);
                    
if(do_auto_run)
{
    emit_string(['Enter','r','u','n','Enter'], 3300, 800);
}
```

it types the 'R' 3300ms after it send the load basic command and presses it for 800ms  then the 'u' also for 800ms long and thereafter the 'n'   

I discovered when I immediatly type 'RUN' after the loading it types nothing .... and mostly the 800ms long press worked ...

maybe as a quick fix we could press each character for 1000ms 🤔... in order to let the c64 Basic register the key press

the main problem is ... my UI code does not know when the Disk loading has finished ... 


maybe the best is to wait on a disk loading finish event ??  


```
function emit_string(keys_to_emit_array, type_first_key_time=200, next_key_time=200)
{  
    time_in_future=type_first_key_time;
    keys_to_emit_array.forEach(function (the_key, i) {
             console.log(the_key);
             var c64code = translateKey2(the_key, the_key.toLowerCase());
             if(c64code !== undefined)
             {
                if(c64code.modifier != null)
                {
                    setTimeout(function() {wasm_key(c64code.modifier[0], c64code.modifier[1], 1);}, time_in_future);
                    setTimeout(function() {wasm_key(c64code.modifier[0], c64code.modifier[1], 0);}, time_in_future+next_key_time-10);
                }

                setTimeout(function() {wasm_key(c64code.raw_key[0], c64code.raw_key[1], 1);}, time_in_future+10);
                setTimeout(function() {wasm_key(c64code.raw_key[0], c64code.raw_key[1], 0);}, time_in_future+next_key_time-10);
                time_in_future +=next_key_time;
             }
        }
    );
}
```

**Comment by mithrendal** [comment]
we have now higher timer values ... that seems to fix it ...

also a call interface was added to directly mount a demo into vc64web
 
https://dirkwhoffmann.github.io/virtualc64web/#http://csdb.dk/getinternalfile.php/190343/monstre.prg
