### ISSUE TITLE
file dialog refinements

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#55]
just did this ... an additional run option for disks ...

![grafik](https://user-images.githubusercontent.com/17108995/91086570-659fd580-e64f-11ea-9312-52e869aa05c6.png)

when both enabled 
types   
ENTER + load"*",8,1 + ENTER
and
ENTER + run + ENTER

Bug for all file types on iOS only:
 when reinserting the same file a second time into file slot ... the file dialog does not appear ... only when changing to another second file and then the first again makes the file dialog appear ...  🙄

**Comment by mithrendal** [comment]
>when reinserting the same file a second time into file slot ... the file dialog does not appear ... only when changing to another second file and then the first again makes the file dialog appear ... 🙄

fixed ...

next todos:
* zip file support ...
* bring a message when an unknown file is inserted  ...

**Comment by mithrendal** [comment]
we need a library for zip support in javascript, there is no built in support for zip in browsers ... I found a very promising zip library called jszip on github https://github.com/Stuk/jszip 

I just did some integration work into the file dialog  ... and dragged a zip file into the file slot ...

![grafik](https://user-images.githubusercontent.com/17108995/91644173-fb65a700-ea39-11ea-9271-5bfc619cb20e.png)


looks promising ...

**Comment by mithrendal** [comment]
published new zip supporting version of vc64web to gh-pages

now it goes like this

1. drag a zip into the file slot

![grafik](https://user-images.githubusercontent.com/17108995/91662893-9a93a880-eae5-11ea-9699-890a93ea544e.png)

it comes up with a file list of the zip contents ... nothing is selected yet,  look at button "mount file" it is disabled

2. select one file

![grafik](https://user-images.githubusercontent.com/17108995/91662917-b9923a80-eae5-11ea-9da2-43350dac58b7.png)

3. click on button mount file 

![grafik](https://user-images.githubusercontent.com/17108995/91662938-ecd4c980-eae5-11ea-94e5-b34f9f6ee140.png)


brings the standard dialog for the file type ... with the usual auto start options ...

**Comment by mithrendal** [comment]
three questions in case of a zip archive ... for further refinement...

Maybe we should disable list items which are not mountable, we could make them visible but not selectable ? 🤔

Also if only one mountable item is in the zip we could theoretically skip the whole zip file selection dialog... ?🤔

Also we could auto select the first mountable list item ? 🤔


or leave the code just like it is now ? 🤔


What do you think ...

**Comment by dirkwhoffmann** [comment]
> Maybe we should disable list items which are not mountable, we could make them visible but not selectable ? 🤔

Yes, I would go this way. Maybe it's best to not display them at all... unsure... 🤔

> Also if only one mountable item is in the zip we could theoretically skip the whole zip file selection dialog... and auto mount that ?🤔

That's the standard case. Hence, yes, skip the selection process. 

> Also we could auto select the first mountable list item ? 🤔

If I remember correctly, vAmiga always picks the first item. There is no way to select anything, because this would have meant to implement an additional file selector. With "auto select" you mean that the first item is always chosen like in vAmiga? Or do you mean to preselect the first item and the user simply has to hit OK to choose it?

> or leave the code just like it is now ? 🤔

I am unsure about the most common use case. Is it intended to use zip files with multiple mountable items in it? We could simply forbid that and/or just use the first item from the archive. Or do you think that it makes sense to support zip files with multiple items? I haven't seen such archives in the wild so far.

**Comment by mithrendal** [comment]
what I did now is ...

1. make all unmountable files visible but unselectable
2. when only one mountable file is in the zip auto select it ...
 

>Is it intended to use zip files with multiple mountable items in it? We could simply forbid that and/or just use the first item from the archive. Or do you think that it makes sense to support zip files with multiple items? I haven't seen such archives in the wild so far.

one picture says it all 😎



![grafik](https://user-images.githubusercontent.com/17108995/91666769-db002000-eaff-11ea-8a11-cb2fe50e9d80.png)


auto select first item would be use less ... even when we sort the items...

seven cities of gold loads first Side1 then later it asks for Side2 ... in vc64web it is all loadable from the same zip archive now ... 😎

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/91666986-b1e08f00-eb01-11ea-8887-ae6c110adb03.png)

**Comment by dirkwhoffmann** [comment]
> one picture says it all 😎

OK, I see. Some real archives are out there 🙄.

> we could have another button "diskswap"
> but another button ..

Hmm, yes, I get your point, but I think less buttons is better. In v4.0 I also try to simplify stuff. I think dragging in the zip file again is OK. It's like changing the disk on a real machine with the exception that the same disk is used every time. 

> capitain goes into the pub now ...

He was caught on camera on his way home 😲:
https://www.youtube.com/watch?v=VJ33XZksSFo

**Comment by dirkwhoffmann** [comment]
Just attached my first zipped cartridge in vc64mac 4.0 😎:

<img width="986" alt="Bildschirmfoto 2020-09-01 um 15 03 42" src="https://user-images.githubusercontent.com/12561945/91854959-cc7f4900-ec64-11ea-9356-aadc7598f243.png">

The unzipping code is the same as in vAmiga. It's not as cool as the one in vc64web, because it always picks the first suitable item found in the zip. Otherwise, I would have had to change too much stuff 🥵.

**Comment by mithrendal** [comment]
>It's not as cool as the one in vc64web, because it always picks the first suitable item found in the zip. 

don't worry bro you have a at least a debugger ... 😎

these two forks are now like iOS and MacOS ... 😅 both can lend some ideas from each other no ?

look what I just did


![grafik](https://user-images.githubusercontent.com/17108995/91895368-6a8c0700-ec97-11ea-86b5-5ae901a712ca.png)

lets click on the empty file slot ...

![grafik](https://user-images.githubusercontent.com/17108995/91896563-5fd27180-ec99-11ea-828e-6aad89cbf0e2.png)

choose the seven_cities zip file 

![grafik](https://user-images.githubusercontent.com/17108995/91895518-a921c180-ec97-11ea-9f3a-e881f21e31e8.png)


![grafik](https://user-images.githubusercontent.com/17108995/91895926-54cb1180-ec98-11ea-97c3-2ce1e73b1a01.png)

game tells me to insert map disk ...

did you spot the difference ? The file slot changed ... it shows that we are operating still inside the zip archive 

lets click the "open zip" thing ...

![grafik](https://user-images.githubusercontent.com/17108995/91896027-8348ec80-ec98-11ea-81e4-ec8d070b5692.png)


wow ... it just opens ... no need to reinsert something from the host system file picker ... this is cool no ?

![grafik](https://user-images.githubusercontent.com/17108995/91896186-bb502f80-ec98-11ea-871f-e9c665be2e44.png)



and after some loading time from map disk .... I am again at the 

![grafik](https://user-images.githubusercontent.com/17108995/91896410-171ab880-ec99-11ea-90a7-7397c3132612.png)


Pub 😳

**Comment by mithrendal** [comment]
![D6588A4E-415F-4D94-9BA6-6B63E2BE2227](https://user-images.githubusercontent.com/17108995/92102402-db8a0680-edde-11ea-9c88-8fbc2f18842b.png)


Zip indicator slightly optimized 😎

**Comment by mithrendal** [comment]
tape loading got also option auto run "typing"

![grafik](https://user-images.githubusercontent.com/17108995/92279887-90641680-eef8-11ea-9c48-7d447f9030d2.png)

it types run + return ...so one must not type it via keyboard...

**Comment by mithrendal** [comment]
![8003B6D6-8383-488C-922C-B8CCD79B9B86](https://user-images.githubusercontent.com/17108995/92308891-57cc4780-efa1-11ea-8b38-ca17c175f886.jpeg)



Another great multidisk title. This one has even more disks, three !!! 🤭

![56547F12-D7E7-485A-89EB-D97E20BBDD98](https://user-images.githubusercontent.com/17108995/92308895-63b80980-efa1-11ea-8358-4f96ef69e1e2.png)


It wants us to insert side 1 into floppy drive ...


Luckily we have it in our already loaded zip archive box. 🤗


![5E22D04A-B778-4928-A1E0-8DD3753F08B5](https://user-images.githubusercontent.com/17108995/92308984-c9a49100-efa1-11ea-9959-ae91c410ba2f.png)


![39F8B1F1-E308-4A63-82E2-67FBB258D618](https://user-images.githubusercontent.com/17108995/92308903-716d8f00-efa1-11ea-8595-e6c39aff16ca.png)

![75BFECB0-74E5-4FD9-A13B-4F3C6708698A](https://user-images.githubusercontent.com/17108995/92308924-81856e80-efa1-11ea-96e9-cceb8f1c54e5.png)

![F0ACF49E-135C-4E35-A8B4-ED54B6F0870A](https://user-images.githubusercontent.com/17108995/92308950-995cf280-efa1-11ea-9f67-8e35965283b0.png)

Works great.

**Comment by mithrendal** [comment]
When I save snap shots in multi disk titles ... the snapshot names are the ones of the disks 😳 like it is with single file titles...

hence on a two disk title where I have to swap often (like zak mac kracken ) ... I end up with two different lines of snapshots in the snapshot browser ... 🙈

**Comment by dirkwhoffmann** [comment]
>  I end up with two different lines of snapshots in the snapshot browser ... 🙈

In vAmiga, I "solved" this by binding the save folder to the first disk inserted after a reset. In VirtualC64 v4.0 I try to do the same, although it is more difficult. E.g., if a Final Cart III is plugged in, we don't want to save screenshots in the Final III folder (because this cart is an auxiliary cartridge). On the other hand, if Frogger is plugged in, we do want to save screenshots in the Frogger folder. 

> Btw: who is the guy with the blue head? Scary!!

Don't know, but he has creepy hair. Oh wait, he doesn't have hair at all. 😳

**Comment by mithrendal** [comment]
that was an easy one 😅 ...


```
 $("#button_insert_file").click(function() 
    {   
...
        //if it is a disk from a multi disk zip file, apptitle should be the name of the zip file only
        //instead of disk1, disk2, etc....
        if(last_zip_archive_name !== null)
        {
            global_apptitle = last_zip_archive_name;
        }
        else
        {
            global_apptitle = file_slot_file_name;
        }

```



the save folder ( internally global_apptitle) for snapshots and custom buttons, is determined  in  the following use cases
 use case 1: on mounting of any file (.prg, .d64, etc ) in the file dialog
 use case 2: on loading a snapshot from the snapshot browser
 use case 3: on manually changing the savefolder name in the take snapshot dialog

exception: when it detects a multidisk zip archive 
  use case 1: takes the name of the zip archive, instead of the mounted file

**Comment by mithrendal** [comment]
>if a Final Cart III is plugged in, we don't want to save screenshots in the Final III folder

I see. 😳 A special case 🤭. In that rare special case we still have use case 3 (see above) no?

**Comment by dirkwhoffmann** [comment]
>  In that rare special case we still have use case 3 (see above) no?🥴

For v4.0 I plan to add a method `Cartridge::mediaID` or something that returns a fingerprint. By default this fingerprint is the checksum of the CRT file. Auxiliary cartridges such as FC III will overwrite this function and return 0 which means that they are not going to change the screenshot target folder. Until v4.0 is out, I think we should ignore this case and go with your three use cases mentioned above.

**Comment by mithrendal** [comment]
with the latest addition of a warning message when no disk rom is installed and the user wants to insert a g64 or d64 file ... I would say it is done and can be closed ... no more refinements for now...
