### ISSUE TITLE
Missing cartridges

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64web#58]
I'd like to expand the range of supported cartridges in v4.0 a bit. For doing this, I am looking for the following cartridges in form of .crt files:

- Moonspire
- GameKiller

Maybe someone can help out (without posting them here).

BTW, v4.0 will support cartridges of type "Dinamic" (which is an extremely simple cartridge, to be honest):

<img width="970" alt="Bildschirmfoto 2020-09-15 um 17 16 19" src="https://user-images.githubusercontent.com/12561945/93230608-265d3400-f778-11ea-9da0-e179a891daa7.png">

**Comment by dirkwhoffmann** [comment]
Oh, this was supposed to be opened in the VirtualC64mac repo. 🙄

**Comment by mithrendal** [comment]
looks like the amiga title "desert storm" on c64 ...🤓
