### ISSUE TITLE
vc64 action script ... part 2

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#60]
ok we have now the aim bot which is described at the end of part 1 ... but it is only working as expected when the sprite is sitting somewhere e.g. in the middle of the playing field... 

unexpected behaviour is arising when we move our joystick to control the movements of the sprite ... our manual movement control actions is obviously interfering with the automatic aim bot code ... 

### example: 
1.we turned the aimbot on
2.we are at the left our opponent is on the right side 
3.we move our sprite down
4.the aimbot 🤖 spots that we are on the same horizontal line as our opponent 😎
5.it aims and shoots: in this case it presses fire and pulls joystick to the right 😍
6. !!! 😱 now the interferring occurs, because we are manually still pulling the joystick downwards, the vc64core receives the aimbots fire press and the pull right and our manual pull down ...😳
7. the game reacts with shooting 45° right  down ... not what we wanted 🙄

so to repair this I have the following idea:
we can connect the javascript to fetch the vc64cores controlports bitmask which do represent the current state of the joystick. wasm_joystick_state(port_nr)

then we alter the aimbot ...
at 4. 
4.1 it should remember the current state of the joystick
4.3 it should release x_axis and y_axis...  
5. do its aiming and shooting ...
5.1 restore the remembered joystick state ..

but maybe this is not so simple as it looks because  between 4.3 and 5.1 the user could alter the joystick movements 🤔 tricky ...  any ideas ?

**Comment by mithrendal** [comment]
okay I think the afore mentioned modifications are not going to work ... maybe they would solve this particular use case but they will introduce new problems e.g. lost joystick commands  ...

going back to the drawing board ... 😅

what we want is 

1. a short interrupt of the normal manual joystick commands which are coming in ... to execute our automatique
2. at the same time we do not want to loose any manual movement ...

therefore I think we have to 
* always record all manual user actions, to know the last joystick state, so as when there were no such an interrupt at all
* when the automatique is going to take over we should temporarily decouple the manual gear from the core 
* when the automatic ends we should restore the last recorded joystick state (even if that was recorded while in automatique mode)

**Comment by dirkwhoffmann** [comment]
Here are my two cents:

Patch the Joystick class as follows:

- Add an enum called JoystickAccessor or GamePadOwner or something like this with two elements: MANUAL, AUTOPILOT (or USER, BOT or similar).
- Enrich all Joystick class functions with an additional JoystickAccessor argument.
- Manage two independent joystick states all the time (one for USER, one for PILOT).
- Add a function setMaster() or setOwner() that  selects the commander in chief.
- According to the current command in chief, return the corresponding states in the polling functions.
- When the auto pilot has to take over, set owner to PILOT and reset it to USER when the script has been processed.

**Comment by mithrendal** [comment]
it works ... here are some fragments 

```
const PORT_ACCESSOR = {
    MANUAL: 'MANUAL',
    BOT: 'BOT'
}

var current_port_owner = {}; 
set_port_owner(1,PORT_ACCESSOR.MANUAL);
set_port_owner(2,PORT_ACCESSOR.MANUAL);

function set_port_owner(port, new_owner)
{
    current_port_owner[port]=new_owner;
}
function send_joystick( accessor, port, command )
{
    if(accessor == current_port_owner[port])
    {
        wasm_joystick(command);
    }
}

function restore_manual_state(port)
{
    wasm_joystick( port_state[port+'x'] );
    wasm_joystick( port_state[port+'y'] );
    wasm_joystick( port_state[port+'fire'] );
}

```

and these methods are used in the aimbot like this ...

```
js:
while(not_stopped(this_id))
{
  await aim_and_shoot(1);
  await action("100ms");
}

async function aim_and_shoot(port)
{ 
  var y_light=sprite_ypos(0);
  var y_dark=sprite_ypos(1);
  var x_light=sprite_xpos(0);
  var x_dark=sprite_xpos(1);

  var x_aim=null;
  var y_aim=null;

  if( Math.abs(y_light - y_dark) <15)
  {
   x_aim=x_light-x_dark > 0 ?'left':'right';   
  }
  if( Math.abs(x_light - x_dark) <15)
  {
   y_aim=y_light-y_dark > 0 ?'up':'down';   
  }
  if(x_aim != null || y_aim != null)
  {
   set_port_owner(port, PORT_ACCESSOR.BOT);
   //clear joystick
   await action(`j${port}left0=>j${port}up0`);

   //aim and shoot
   await action(`j${port}fire1`);
   if(x_aim != null)
     await action(`j${port}${x_aim}1`);
   if(y_aim != null)
     await action(`j${port}${y_aim}1`);
   await action("300ms");
   if(x_aim != null)
     await action(`j${port}${x_aim}0`);
   if(y_aim != null)
     await action(`j${port}${y_aim}0`);
   await action(`j${port}fire0`);
   restore_manual_state(port);

   //give manual control back to the user
   set_port_owner(port,PORT_ACCESSOR.MANUAL);   
  }
}

```

**Comment by dirkwhoffmann** [comment]
>  Is it not always good to call it when set_port_owner(port,PORT_ACCESSOR.MANUAL);

Yes, it should be enough to call it there.

**Comment by mithrendal** [comment]
Ok I did that ...

I spotted two bugs which I just fixed ... one was simply that a deletion of an action button was not persisted to the database 🙄

The other bug was in the collection of the joystick state for the new restoration code of the manual joystick state after the bot handed control back to the user ... that bug was so weird and hard to find that I want to present it here ....

the bug did effectively prevent that diagonal movements were correctly restored ...

what you could see in the debugger was that 1x had values for the y axis for example 
 port_state['1x'] == PULL_UP
 
here is the faulty code



   ```
 if(cmd == "PULL_RIGHT")
    {
        port_state[port+'x'] = cmd;
    }
    else if(cmd == "PULL_LEFT")
    {
        port_state[port+'x'] = cmd;
    }
    else if(cmd == "RELEASE_X");
    {
        port_state[port+'x'] = cmd;
    }

    if(cmd == "PULL_UP")
    {
        port_state[port+'y'] = cmd;
    }
    else if(cmd == "PULL_DOWN")
    {
        port_state[port+'y'] = cmd;
    }
    else if(cmd == "RELEASE_Y")
    {
        port_state[port+'y'] = cmd;
    }
```


can you find the bug ? do you want the solution ? 🤓

**Comment by mithrendal** [comment]
it is not 45° 😱 ...

the angle is wrong ... the aim bot aims far off ...

look here ... I turned wide screen off so the aspect ratio should be fine ...

![grafik](https://user-images.githubusercontent.com/17108995/94607082-bbdde500-029b-11eb-9a43-f519d792305e.png)

I only compared pixel differences ... does the y pixel have a different size compared to the x pixel 😳... in other words ... is it not quadratic ? 🤔


```
js:
while(not_stopped(this_id))
{
  await aim_and_shoot(1);
  await action("100ms");
}

async function aim_and_shoot(port)
{ 
  var y_light=sprite_ypos(0);
  var y_dark=sprite_ypos(1);
  var x_light=sprite_xpos(0);
  var x_dark=sprite_xpos(1);

  var y_diff=Math.abs(y_light - y_dark);
  var x_diff=Math.abs(x_light - x_dark) ;

  var x_aim=null;
  var y_aim=null;
  

  if( y_diff<10 || Math.abs(x_diff - y_diff) <10)
  {
   x_aim=x_light-x_dark > 0 ?'left':'right';   
  }
  if( x_diff <10 || Math.abs(x_diff - y_diff) <10)
  {
   y_aim=y_light-y_dark > 0 ?'up':'down';   
  }
  
  if(x_aim != null || y_aim != null)
  {
    set_port_owner(port, PORT_ACCESSOR.BOT);
    await action(`j${port}left0=>j${port}up0`);

    await action(`j${port}fire1`);
    if(x_aim != null)
     await action(`j${port}${x_aim}1`);
    if(y_aim != null)
      await action(`j${port}${y_aim}1`);
    await action("300ms");
    if(x_aim != null)
      await action(`j${port}${x_aim}0`);
    if(y_aim != null)
      await action(`j${port}${y_aim}0`);
    await action(`j${port}fire0`);
    await action("100ms");

    set_port_owner(port,PORT_ACCESSOR.MANUAL);
    await action("500ms");
  }
}

```

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/94669895-2893c680-0312-11eb-8642-9b27695d034c.png)

when I double the y_diff it shoots perfect ... now a killer machine bot 😎

... but why ? 

Question: is the angle really different to 45°  or  is the width of an pixel twice its height?

**Comment by dirkwhoffmann** [comment]
>  is the width of an pixel twice its height?

Strange. The width and height of a pixel are approx. the same. 🤔

**Comment by mithrendal** [comment]
thanks, if thats the case ... then the angle can not be 45°, right ? 

tan(angle) = y_diff/ x_diff   => angle = atan(y_diff/x_diff)   right?

hmm 🙆 lets see what the angle is ... by trying out and adjusting the angle until it hits the target ....

```
js:
while(not_stopped(this_id))
{
  await aim_and_shoot(1);
  await action("100ms");
}

async function aim_and_shoot(port)
{ 
  var y_light=sprite_ypos(0);
  var y_dark=sprite_ypos(1);
  var x_light=sprite_xpos(0);
  var x_dark=sprite_xpos(1);

  var y_diff=Math.abs(y_light - y_dark);
  var x_diff=Math.abs(x_light - x_dark);
  var angle = shoot_angle(x_diff,y_diff);

  var x_aim=null;
  var y_aim=null;
  if( y_diff<10 || 26<angle && angle<28 )
  {
   x_aim=x_light-x_dark > 0 ?'left':'right';   
  }
  if( x_diff <10 || 26<angle && angle<28)
  {
   y_aim=y_light-y_dark > 0 ?'up':'down';   
  }
  
  if(x_aim != null || y_aim != null)
  {
    set_port_owner(port, 
      PORT_ACCESSOR.BOT);
    await action(`j${port}left0=>j${port}up0`);

    await action(`j${port}fire1`);
    if(x_aim != null)
     await action(`j${port}${x_aim}1`);
    if(y_aim != null)
      await action(`j${port}${y_aim}1`);
    await action("60ms");
    if(x_aim != null)
      await action(`j${port}${x_aim}0`);
    if(y_aim != null)
      await action(`j${port}${y_aim}0`);
    await action(`j${port}fire0`);
    await action("60ms");

    set_port_owner(
      port,
      PORT_ACCESSOR.MANUAL
    );
    await action("500ms");
  }
}

function shoot_angle(x, y) {
  return Math.atan2(y, x) * 180 / Math.PI;
}

```

this script also kills 100% secure on diagonal ... I can already see that the computer opponent does not laugh at my poor combat skills anymore 😎

🙋🏻that means that archons diagonal shooting angle seems to be 27°, no ?

**Comment by dirkwhoffmann** [comment]
I don't understand this. The bot is supposed to shoot when both players are on a common diagonal (dx == dy). Right? But the issue is that the sprite coordinate deltas don't seem to match when the players are on a common diagonal?

**Comment by mithrendal** [comment]
yes and yes ...
I first thought it had to shoot on 45° that is when dx==dy then but the shoot did not hit the target then it was off ... see first picture

then I altered it to shoot when dy*2 == dx ... that worked

in the last try I used trigonometric maths 

then when the bot shoots at 27° the result is the same as with dy*2 == dx ... that is aehm deadly for the target

**Comment by dirkwhoffmann** [comment]
> then when the bot shoots at 27° the result is the same as with dy*2 == dx ... that is aehm deadly for the target

OK, I see, this means that if I shoot in Archon, the bullet doesn't travel along the diagonal. Correct?

**Comment by mithrendal** [comment]
yes

**Comment by mithrendal** [comment]
I just used a physical triangle ruler ("Geodreieck") and measured the travel of the bullet in the first picture of the issue

the blue djinni stands on 45° and the bullet is on 27° ... that is the proof I would say ...

I would say we just reverse engineered archons shooting angle ... 😍

**Comment by dirkwhoffmann** [comment]
> "Geodreieck"

I love the old tools from back in the day 🤓. Nothing to configure, no Wifi issues whatsoever. Very reliable. It just works. 😎

**Comment by mithrendal** [comment]
remains the question why the devs choose the bullet travel angle of 27° ...

**Comment by mithrendal** [comment]
time for some cosmetics .... I made the text input area for script wider ... when inserting "js:" to write javascript we do auto adjust the height and give it a min-height of 300px

we have now  new template category "javascript" more script templates for the javascripts will be coming ... 

the first is "simple while" ... later we can add "auto defense control", "aim-bot", etc ...

![grafik](https://user-images.githubusercontent.com/17108995/94730952-5275d900-0364-11eb-8517-0630e224f8c2.png)

**Comment by mithrendal** [comment]
introducing key shortcuts for action buttons ... 😎 

![grafik](https://user-images.githubusercontent.com/17108995/94859737-4f96e900-0435-11eb-8491-774ce0ca49a1.png)

these key short cuts are of optional ... 

see here is the empty definition dialog ... 

![grafik](https://user-images.githubusercontent.com/17108995/94860114-e19ef180-0435-11eb-9f0b-4283ae13b243.png)

**Comment by mithrendal** [comment]
### global scoped action buttons
we now can choose to make action buttons global or app specific 😎

there is a new setting in the action button definition dialog ... 

![grafik](https://user-images.githubusercontent.com/17108995/95000508-a4676a80-05c1-11eb-961b-f121d42e4417.png)

to get a feeling which button is global and which is app specific I decided to give the global buttons a thick gray border ... look here 4 global scoped buttons and one app specific button

![grafik](https://user-images.githubusercontent.com/17108995/95000438-260ac880-05c1-11eb-9ea1-78789864f17b.png)


### javascript templates 
also new in this release more "javascript templates"

![grafik](https://user-images.githubusercontent.com/17108995/95000569-63238a80-05c2-11eb-9b44-501a82e4808f.png)

I included the archon aimbot 😍 ... stay tuned there are more to come (the next will be falcon patrol auto defense I think 😅)

**Comment by dirkwhoffmann** [comment]
> we now can choose to make action buttons global or app specific 

Cool concept 😎. It reminds me on the MacBook Touch Bar. The global buttons are those that are available to all apps (e.g., volume control) and the others vary between applications.

**Comment by mithrendal** [comment]
I think this is done ... it works nicely ...
