### ISSUE TITLE
streamlining the call interface

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#63]
I could not resist to add a keyboard shortcut to the filedialog 

![grafik](https://user-images.githubusercontent.com/17108995/97047088-b6ad4680-1578-11eb-9eb1-fb3b3ed599c2.png)

whenever the file popup comes up we can just hit on the enter key and it proceeds ...😎 

e.g.  just click 

https://dirkwhoffmann.github.io/virtualc64web/#http://csdb.dk/getinternalfile.php/190343/monstre.prg

and hit the enter key

**Comment by mithrendal** [comment]
A lot of demos at csdb write explicitly the preference of sid model 8580. why is that ? Is the 6581 not good enough?🤔

Anyway I thought there should be a new setting for this. 

![E2FA60E9-0576-4595-8738-BC661C624766](https://user-images.githubusercontent.com/17108995/97118042-33225f80-1708-11eb-9592-955f19ed8735.jpeg)

**Comment by mithrendal** [comment]
![43D9694E-1302-4FCF-9864-CE796E88508B](https://user-images.githubusercontent.com/17108995/97118620-484cbd80-170b-11eb-8d74-a1738243c597.jpeg)


Wow. In this cool sound track the 8580 really makes a great difference...😎

**Comment by dirkwhoffmann** [comment]
>  In this cool sound track the 8580 really makes a great difference...😎

I don't know where the differences come from. From a coders point of view, both SIDs are identical. 

The old versions of VirtualC64 had the problem that filter emulation was buggy for one the two SID revisions (don't remember which one), but in the latest release of VICE they have fixed this. The v3.4 core uses the latest reSID code. I think this is the core VirtualC64web is based on.

**Comment by mithrendal** [comment]
> The v3.4 core uses the latest reSID code. I think this is the core VirtualC64web is based on.

I have looked into vc64mac, there are two branches 

* 3.4 has 2 years old resid code
* resid3.4 has some resid files which are 4 months old ...
* master all resid files are 4 months old
 
I double checked this with vc64web ... here master only  has 2 years old files ... same as branch 3.4 

Do I have to copy the new resid files of branch resid3.4 or master ? Is master still the 3.4 version or already 4.0?

**Comment by dirkwhoffmann** [comment]
> 3.4 has 2 years old resid code

Strange. 🤔

I've already merged back the v4.0 branch to the master branch a couple of times, so most of the v4.0 stuff is already part of it.

> Should I already upgrade to version 4, I guess it is in branch dev, no?

I think it's best if you only copy the reSID stuff from the master branch to VC64web at the moment, because the v4.0 API is already slightly different to the v3.4 API and is likely to change further. Hence, if you do the API adjustments now, you need to do them again once the v4.0 branch has been finalized which is unnecessary extra work.

**Comment by mithrendal** [comment]
copied the resid files from master and it compiled without issues ... that was easy ...


now I think a share button on the csdb detail view could be useful ... one which copies the link to the clipboard  
e.g.

https://dirkwhoffmann.github.io/virtualc64web/#http://csdb.dk/getinternalfile.php/139416/LMan%20-%20Vortex.prg

...lets see how that works ...

**Comment by mithrendal** [comment]
we got now these copy to clipboard buttons ... for sharing cool music or demos via messenger, blog or mail ...

![grafik](https://user-images.githubusercontent.com/17108995/97221723-988c5400-17cd-11eb-83cd-446e6cc0f7db.png)

**Comment by mithrendal** [comment]
I think blue completely transparent buttons for copy to clipboard is looking more modern ... 

![grafik](https://user-images.githubusercontent.com/17108995/97487237-e4213800-195c-11eb-8ab4-a914e4bb5b13.png)

**Comment by mithrendal** [comment]
when we have set vc64web in pause ... and then later clicked a snapshot or a csdb entry .. nothing happened ... because it was still in pause ...

I altered that ... vc64web will be set into running mode which feels more to be the natural right thing as the user clicks on something, because he wants action ... 


![grafik](https://user-images.githubusercontent.com/17108995/97492263-93610d80-1963-11eb-92d5-5466c15cb20e.png)
 
Gimme some action now ! 😎

**Comment by mithrendal** [comment]
I am just blown away by the following outstanding demo

![D3CFB0A8-3FF9-4143-B6A7-82A9E368E9BF](https://user-images.githubusercontent.com/17108995/97631477-56fbe300-1a31-11eb-85ec-6917373c0b1f.jpeg)


Edge of disgrace 

What a monster in sound graphics and art departement  🤤🤤🤤


https://dirkwhoffmann.github.io/virtualc64web/#http://csdb.dk/getinternalfile.php/67631/EdgeOfDisgrace.zip

**Comment by mithrendal** [comment]
we now show rom dialog on startup only when one of these points is true

* any required system rom is missing, e.g. kernal, characters, basic
* when optional floppy system rom is missing and call_parameter links to a  .d64 or .g64 file
* when optional floppy system rom is missing and there is no call_parameter at all

🤔 does the last point makes sense ?

**Comment by dirkwhoffmann** [comment]
> does the last point makes sense ?

Yes, I think it makes sense. Of course, we could simply disconnect the drive if the drive Rom is missing, but the user could  get confused when the drive is not working. He might think it's due to an emulator bug and not due to a missing Rom.

**Comment by mithrendal** [comment]
in case call_parameter is set to a 
   .zip
with multiple entries... we must bring up the file dialog...

same is true I think for d64/g64 files because you can choose to look into their directories ... with load"$",8:list

but what about call_parameter ending with .prg, .crt, .t64 and .tap ? Is it reasonable to bring up the file dialog for these too ? Or should it be skipped for these file types? 

On the one hand it is nice tha it always behaves the same and upon iinsert something or calling something that you can be sure that when loading was fine that it brings always this file dialog ...

On the other hand this extra click or ENTER could be avoided...

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/97908278-c4b45180-1d46-11eb-9fa4-9f6c742cee8f.png)

we are showing all the comments and the summary to each csdb entry ... 😎

**Comment by mithrendal** [comment]
I think the csdb.dk interface in vc64web works really nice by now. I am really happy with it ... and using it is currently a pleasure because they currently have this ECM compo running ... with putting out new hot freaking cool demos every day ...  🤤🤤🤤 unbelievable what is possible with C64 hardware ...


![grafik](https://user-images.githubusercontent.com/17108995/97981220-3ab1ca80-1dd2-11eb-991b-54ed526b3c04.png)




Technically we have now abstracted all the parts of querying and fetching and showing the details into a so called "collector" interface so connecting to https://demozoo.org as @emoon with vAmiga should be just another implementation for the existing UI interface and mechanics...  once we compiled and connected the vAmigaCore to it ... everything should be very reusable ... I hope

But before going into vAmiga ... we should add two features to the "collector" interface which come to my mind

* first is search ... the interface for a db collector should be able to support search ... csdb also has an nice webservice interface for this ... and searching into locally stored snapshot titles would be also cool

* second is favourites ... we let the user set a "heart" for a title ... technically we remember the id's of the users favourites in our webapps database and fetch all entries one by one ... this first sounds like this will give a slow load performance but it is not because we will intensely use PWA web caching for this ... csdb.dk has a webservice API to query single titles which I already use by now ...

**Comment by dirkwhoffmann** [comment]
> But before going into vAmiga ...

Yes, let's focus on the C64 first. It's not like the vAmiga core isn't ready yet, but once two web emulator exist, it's twice the work to maintain them. Therefore, I thinks it's best to wait until things stabilize. 

> BTW: this is really nice https://dirkwhoffmann.github.io/virtualc64web/#http://csdb.dk/getinternalfile.php/205484/elite-code-mechanics.prg

Clicking this link worked flawlessly here (it's really cool that the browser remembers the Roms 😎). The only interaction I had with the emulator was the "Auto run" checkbox. I was wondering if we could somehow get rid of this. Since we want to attract new users, the "first encounter" with the emulator is essential. It would be super cool if the demo just starts out of the box, especially because new users might not understand what "auto run" is.

**Comment by mithrendal** [comment]
> I was wondering if we could somehow get rid of this

I think to skip the auto run option dialog when coming via call_parameter is super easy ... we could skip it if the link is an prg, crt, t64 or tap file ...  in case of zip or d64 we just leave it as it is ... as the user wants to look inside the disk or zip ...

also we could alter or optimise the system rom dialog which pops up when a user for the very first time started vc64web ... then generally no roms are in the sockets ... the problem: what if the user decides not to install original roms nor to hit the "install open roms"-button ... when he just clicks the "close" button or ESC-key ? then currently the emulator refuses to run and the user just sees a black emulator canvas ... 

I see four ways to avoid this...

1. if there are no required roms ... automatically install open roms without asking the user ... and show the rom dialog
or
2. if there are no required roms ... automatically install open roms without asking the user ... and don't show the rom dialog
or
3. show the rom dialog with the empty sockets and when the user chooses to leave the dialog without having installed anything -> don't let him leave with a message that he must install first ... 
or
4. show the rom dialog with the empty sockets and when the user chooses to leave the dialog without having installed anything -> install the open roms ...

hmm what do you think is the best ? Maybe when called via csdb link (2.) and when not called with parameter 1,3 or 4 ?...

>...Since we want to attract new users ...

I somehow doubt that these changes above will increase the awareness of the existence of the web emulator or attract new users ... 😄
 
the point is that vc64web is simply still completely unknown by the scene ... (ok except Klaus) 🤓

when looking into the forums at csdb ... they currently like to have a thing like vc64web ... look here for example is a discussion thread from october 2020 on csdb.dk  https://csdb.dk/forums/?roomid=5&topicid=140020&firstpost=17  where they discuss on making it more modern ...

this post nails it 

`I get the impression that the people that want updates are looking for a more modern look, and a smoother experience, and are not the kind of users that actively add content to the database, or in other ways are contributing to the database work by spending time on updating info and entries. That is why C64 Scene by Mr.SID or JCH's project is the way to go. Keeping CSDb intact but gives the ones that feel a need for a more modern look what they "need". :)
`

but we can not reach out to them and tell them about our vc64web csdb scene browser as we have no account on csdb ... only "real"💪🏼 sceners get one 🙄 ... I only did some basic programs with a lot poke and data commands for the sprites and some short assembler programs with smon on the c64 back in the days  ... which are all lost by now 🙈 ... maybe one stumbles by chance about our vc64web scene browser tool ...

**Comment by mithrendal** [comment]
> The only interaction I had with the emulator was the "Auto run" checkbox. I was wondering if we could somehow get rid of this

ok I have a dev build now on my computer which always (vc64web called with or without parameter) skips the auto_run options for .crt .t64 and .prg files ...

should I deploy it ? we can also make it skip only when called with parameter or we could introduce a setting for it ...

**Comment by mithrendal** [comment]
pushed out a new version ...

* don't show the auto-run option dialog on .prg .crt .t64 files 
* we optimized timings for open-roms (they provide shorter system start timings) so switching between demos is even faster ... although not that compatible
* for first time users ... when they click away the rom-dialog without specifying the three required system roms ...  then vc64web anyway just loads the open-roms to be able to start the demo in the call parameter if provided  (solution 4. from above ... was one of the easiest to implement ... 🙊)
