### ISSUE TITLE
supercharge ready to type ...

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64web#79]
currently ready to type depends on this code inside vc64_ui.js ...

```
        var faster_open_roms_installed = JSON.parse(wasm_rom_info()).kernal.startsWith("mega");
        if(reset_before_load == false)
        {
            //the roms differ from cold-start to ready prompt, orig-roms 3300ms and open-roms 250ms   
            var time_since_start=Date.now()-wasm_first_run;
            var time_coldstart_to_ready_prompt = faster_open_roms_installed ? 500:3400;
            
            if(time_since_start>time_coldstart_to_ready_prompt)
            {
                execute_load();
            }
            else
            {
                setTimeout(() => {  
                    execute_load();
                }, time_coldstart_to_ready_prompt - time_since_start);
            }
        }
        else
        {
            var time_reset_to_ready_prompt = faster_open_roms_installed ? 800:2800;
            
            $('#alert_reset').show();
            wasm_reset();
            setTimeout(() => {
                execute_load();
                $('#alert_reset').hide();
                reset_before_load=false;
            }, time_reset_to_ready_prompt);
        }
    }

```

since execution time could be interrupted on slow machines or while heavy computing takes place ... the time based approach is a rather not so robust  ...

@dirkwhoffmann brought up a better and safer approach for the "ready to type" state of the Core ... and that is that the javascript can query the already executed cycles so far and make the assumption for the "ready to type state" based on that information rather then the passed time ...

**Comment by mithrendal** [comment]
the cpu cycle dependent 'ready to type' is  implemented ... and pushed to the v4clean branch ... it should be much more robust and deterministic now ...

**Comment by dirkwhoffmann** [comment]
The new keyboard API has been checked in on the dev branch:

Here is the relevant API part:


```C++
    // Presses a key
    void press(long nr);
    void pressRowCol(u8 row, u8 col);
    void pressShiftLock() { shiftLock = true; }
    void pressRestore();

    // Releases a pressed key
    void release(long nr);
    void releaseRowCol(u8 row, u8 col);
    void releaseShiftLock() { shiftLock = false; }
    void releaseRestore();
    
    // Clears the keyboard matrix
    void releaseAll();
    

    //
    // Auto typing
    //
    
public:
    
    void scheduleKeyPress(long nr, i64 delay);
    void scheduleKeyPress(u8 row, u8 col, i64 delay);
    void scheduleKeyRelease(long nr, i64 delay);
    void scheduleKeyRelease(u8 row, u8 col, i64 delay);

```


To understand how the new API works, it's easies to have a look at how the Swift GUI utilizes it.

Here is the function for pressing a single key: 

```Swift
    func pressKey(_ key: C64Key, duration numFrames: Int? = nil) {
    
        // Press key
        keyboard.pressKey(key.nr)

        //Schedule the key release
        if numFrames != nil {
            keyboard.scheduleKeyRelease(key.nr, delay: numFrames!)
        }
    }
```

If two keys need to pressed (e.g., SHIFT-2), here is how to do it: 

```Swift
   func pressKeys(_ keys: [C64Key], duration numFrames: Int? = nil) {
        
        // Press keys
        for key in keys {
            keyboard.pressKey(key.nr)
        }
        
        //Schedule the key releases
        if numFrames != nil {
            for key in keys {
                keyboard.scheduleKeyRelease(key.nr, delay: numFrames!)
            }
        }
    }
```


Finally, here is how the auto-typing feature is implemented in vc64mac:

```Swift
    func type(_ string: String?, initialDelay seconds: Double = 0.0) {
        
        if var truncated = string {
            
            // Shorten string if it is too large
            if truncated.count > 2048 {
                truncated = truncated.prefix(2048) + "..."
            }

            // Set the initial delay for the first key (in frames)
            var delay = Int(seconds / 50.0)

            // Record events
            for c in truncated.lowercased() {

                let keyList = C64Key.translate(char: String(c))
                
                // Press keys
                for key in keyList {
                    keyboard.scheduleKeyPress(atRow: key.row, col: key.col, delay: delay)
                    delay = 0
                }
                delay = 1

                // Release keys
                for key in keyList {
                    keyboard.scheduleKeyRelease(atRow: key.row, col: key.col, delay: delay)
                    delay = 0
                }
                delay = 1
            }
        }
    }    
}
```

**Comment by mithrendal** [comment]
the advantage of the new api vs the current timing based approach in javascript is that the new one is dependend on the executed frames and not anymore exactly timed in the passed miliseconds, right  ? So when something slows down the machine then the keypresses would not get lost with the new approach right ?

**Comment by dirkwhoffmann** [comment]
> is that the new one is dependend on the executed frames

Exactly. Timing is now based on "emulator time" rather than real time.

**Comment by mithrendal** [comment]
implemented 😎 wow it types superfast ...


but a problem ...
![grafik](https://user-images.githubusercontent.com/17108995/102918405-219ad100-4487-11eb-8e71-528fb0a4d8a4.png)


the run is missing ...
before I scheduled it 4500ms after the load ... but new API is not allowing me to do so... because it would result in 90 frames where it is limited to 49 frames ...


![grafik](https://user-images.githubusercontent.com/17108995/102918748-cfa67b00-4487-11eb-97bc-670e1be76a62.png)


maybe 49 is not sufficient ? I bet it needs its 90 frames delay ? How do you delay and type run in vc64mac?

**Comment by mithrendal** [comment]
when I patch the Keyboard.cpp and increase the assertion guard to lets say 150 then it lets pass the needed 90 frames delay for the run ... and everything works as expected .... why only 49 ?

```

void
Keyboard::_scheduleKeyAction(bool press, long nr, i64 delay)
{
    assert(delay < 150);

    debug(KBD_DEBUG, "Recording %d %ld %lld\n", press, nr, delay);

    addDelay(delay);
    actions.push(KeyAction(press, nr, 0));
}

void
Keyboard::_scheduleKeyAction(bool press, u8 row, u8 col, i64 delay)
{
    assert(delay < 150);
    
    debug(KBD_DEBUG, "Recording %d %d %d %lld\n", press, row, col, delay);
    
    addDelay(delay);
    actions.push(KeyAction(press, row, col, 0));
}
```

**Comment by dirkwhoffmann** [comment]
>  why only 49 ?

That was supposed to be a type check, only (the old implementation used microseconds whereas the new measures in frames). I thought nobody wants to delay a key press by more than 1 sec. Just remove the assertion.

You could also wait until the IEC bus gets idle again. This would be safer, because it decouples real time from emulation time.

**Comment by mithrendal** [comment]
peridocally check iec.isBusy() until not busy ? is that ok ?

**Comment by mithrendal** [comment]
I have an idea .... the iec bus is preventing the c64 to receive keyboard events right ? why do we not solve this inside the scheduleKeyAction ? I mean we just halt execution of scheduled keys when iec.isBusy() ... no good idea?

**Comment by dirkwhoffmann** [comment]
> or should I act on the events and set a global javascript variable busy, not busy accoring to the received events?

I think that's the better approach. Register something like a "IEC idle event" somewhere in your code that gets fired when MSG_IEC_IDLE comes in.

**Comment by mithrendal** [comment]
I have build this now ... 

```

                    emit_string(['Enter','l','o','a','d','"','*','"',',','8',',', '1', 'Enter']);
                    if(do_auto_run)
                    {
                        fire_on_message("MSG_IEC_BUS_BUSY",function() {
                            fire_on_message("MSG_IEC_BUS_IDLE", function() {
                                emit_string(['Enter','r','u','n','Enter'],0); 
                            })
                        });
                    }
```


but it is not working .... because when this 

![grafik](https://user-images.githubusercontent.com/17108995/102930601-0c30a180-449d-11eb-867a-4313a3a12fa8.png)


is complete than we can see that those messages happened  

![grafik](https://user-images.githubusercontent.com/17108995/102930470-c2e05200-449c-11eb-8fba-48565d602a02.png)

we see it goes like this ... BUSY->IDLE->BUSY->IDLE

**Comment by mithrendal** [comment]
coool ... it works with the 4 times cascade ... 😂 

but are the events always come in this way ?

**Comment by mithrendal** [comment]
now let see whether it works with tape files ...

oh no ... there is no busy state ... look 

![grafik](https://user-images.githubusercontent.com/17108995/102932681-0b017380-44a1-11eb-937e-a3e6d5cd03e5.png)

**Comment by mithrendal** [comment]
tape file is even more worse than I thought ... the openroms does not auto run in the current 3.4 production version either ... the open-roms team changed something 🤔... original roms of course (not changed in last 30 years) still works fine with the old timeout approach ...

because of this I came with another idea look at this ...

```

if(file_slot_file_name.endsWith('.tap'))
{
    //shift + runStop
    emit_string(['Enter','ShiftRunStop']);
    
    if(do_auto_press_play)
    {
        //press play on tape shortly after emitting load command
        setTimeout(function() {wasm_press_play(); },650);
    }

    if(do_auto_run)
    {
        fire_when_no_more_message("MSG_VC1530_PROGRESS",function() {
            emit_string(['Enter','r','u','n','Enter']);
        });
    }
}
```
I tested it and it works this way ... but when loading choplifter.tap there is a 7 second hole where nothing happens

look here 

![grafik](https://user-images.githubusercontent.com/17108995/102938859-65083600-44ad-11eb-8075-cdbb21ae4cf7.png)

therefore I wait when there was no   MSG_VC1530_PROGRESS in that last 8 seconds.... yes and that made the tape load ... but I am not sure whether this will be an approach that works with all tapes ...


maybe it is better to not auto run tape files at all when using open roms and go with the delayed approach in case of orig roms ?

**Comment by mithrendal** [comment]
When I use scheduleKeyPress for the virtualKeyboard how to schedule the scheduleKeyRelease for the Restore key ?

if that is not possible I will just use the old way in that case ...

**Comment by dirkwhoffmann** [comment]
The "press" and "release" APIs offer two methods to specify a key: 1) By row/col, 2) by key number. There are two C64 keys that are not part of the keyboard matrix and therefore cannot be accesses via a row/col pair: Restore and Shift-Lock. These keys can be pressed and released using the methods accepting a key number. Just provide the correct key number for the restore key which is 31.

Here you can see how these two special keys are handled internally:

```C++
void
Keyboard::_release(long nr)
{
    debug(KBD_DEBUG, "_release(%ld)\n", nr);

    assert(nr < 66);
    
    switch (nr) {
        case 34: releaseShiftLock(); return;
        case 31: _releaseRestore(); return;
        default: _releaseRowCol(rowcol[nr][0], rowcol[nr][1]);
    }
}
```
